SSL-Roots/consai_ros2

- .docker/Dockerfile
- .docker/README.md
- .docker/build.sh
- .docker/ros_entrypoint.sh
- .github/workflows/build_docker_image.yaml
- consai_visualizer/resource/visualizer.ui
Dockerを用いてCON-SAIを開発できるようにDockefileとREADMEを追加します。
> Docker開発環境を追加

- consai_visualizer/src/consai_visualizer/field_widget.py
ボールプレースメントでの進入禁止エリアを描画描画します。
進入禁止エリアは、正しく描画するとドーム型になるのですが、実装が手間なので長方形で描画してます。
ルール：https://kkimurak.github.io/ssl-rules-ja/sslrules.html#_%E3%83%9C%E3%83%BC%E3%83%AB%E9%85%8D%E7%BD%AE%E3%81%B8%E3%81%AE%E5%B9%B2%E6%B8%89ball_placement_interference
> ボールプレースメントでの目標位置と進入禁止エリアを描画

- consai_robot_controller/src/field_info_parser.cpp
> 衝突回避の条件を追加

- consai_robot_controller/src/controller_component.cpp
- consai_robot_controller/src/field_info_parser.cpp
> パスの蹴り出し角度を修正

- consai_examples/CMakeLists.txt
- consai_examples/consai_examples/field_observer.py
- consai_examples/tests/test_field_observer.py
- consai_examples/tests/tracked_frame_publisher.py
#70 をデバッグするためにユニットテストファイルを追加します。
-> 作業の過程で#70 が修正されました。
また、テスト実装時に見つかった下記の不具合を修正します。
- パサー（my_robot_id）が存在しないときにIndexErrorが発生する
- パサー以外が存在しないときにIndexErrorが発生する
- our_robots_velの型チェックをid=0で行うため、0番ロボットが消えた場合に計算がスキップされる
- _forawrd_robots_id()にて、ロボット速度が0のときゼロ除算エラーが発生する
- テストを実行するため、field_observer内のimport文を修正してます。-> [a3a9484](https://github.com/SSL-Roots/consai_ros2/pull/73/commits/a3a9484696479b1bc3eccf3dcf24fa3751632d9a)
- field_observerから未使用の関数を削除しています
- game.pyが問題なく動作することを確認してます。
> field_observerのユニットテスト追加とget_receiver_robots_idの修正

- consai_examples/consai_examples/decisions/sub_attacker.py
> サブアタッカーが、ボールプレースメントでボールを受取り続けるように修正

- consai_visualizer/resource/visualizer.ui
> ロボット台数とカードのフォントを大きくした

- consai_examples/consai_examples/referee_parser.py
- consai_robot_controller/src/field_info_parser.cpp
> penaltyでゴーリーがボールを避けないように、referee_perserでpenalty_inplayをinplayとして扱う

- consai_examples/consai_examples/decisions/goalie.py
- consai_examples/consai_examples/field_observer.py
- もしボールが動いていると判定すればゴールとボールのライン上へ移動
- ボールが動いていなく，ディフェンスエリアにあればパス
> ゴーリーの行動を修正(リフレクトシュートせずゴール前を守る)

- consai_visualizer/src/consai_visualizer/field_widget.py
> ペナルティーマークを描画

- consai_robot_controller/include/consai_robot_controller/controller_component.hpp
- consai_robot_controller/include/consai_robot_controller/field_info_parser.hpp
- consai_robot_controller/src/controller_component.cpp
- consai_robot_controller/src/field_info_parser.cpp
- consai_visualizer/src/consai_visualizer/field_widget.py
- consai_visualizer/src/consai_visualizer/visualizer.py
`goal_pose` : 衝突回避やボール受取によって変化する目標姿勢
`final_goal_pose` : 最終的にたどり着きたい目標姿勢
をpublishして描画します。
> 最終移動目標姿勢をfinal_goal_poseとしてpublishする。それを描画する

- consai_examples/consai_examples/field_observer.py
- consai_examples/consai_examples/geometry_tools.py
- consai_examples/tests/test_geometry_tools.py
- field_observer.py
- 表記の通り
- パス関数も調整した
- geometry_tools.py
- リストからPose2Dへ変更
- test_geometry_tools.py
-  geometry_tools.pyの変更についてテストを書き換え・追加
> ロボットの位置・速度をリストからPose2Dに変更とIDをコールバック関数で取得に変更

- consai_robot_controller/launch/test.launch.py
- consai_visualizer/src/consai_visualizer/field_widget.py
- consai_visualizer/src/consai_visualizer/visualizer.py
ビジュアライザにinvertフラグを追加し、サイド反転に対応します。
ボールのgrsim、replacementと　ボールプレースメントの描画に対応します。
> ビジュアライザがサイド反転に対応

- consai_robot_controller/config/control_params.yaml
- consai_robot_controller/include/consai_robot_controller/field_info_parser.hpp
- consai_robot_controller/src/controller_component.cpp
- consai_robot_controller/src/field_info_parser.cpp
control_ball関数のアルゴリズムを変更します
また、control_ballで使用する変数をROSパラメータ化します。
> control_ballアルゴリズム変更、変数をROSパラメータ化

- consai_robot_controller/src/field_info_parser.cpp
> キックパワーを弱くした

- consai_examples/consai_examples/decisions/attacker.py
- consai_examples/consai_examples/field_observer.py
- consai_examples/consai_examples/robot_operator.py
壁際（PR作成時点ではフィールド外かどうか）で実装
実機の様子見て要調整
> 壁際のボールプレースメントの実装

- consai_examples/consai_examples/decisions/decision_base.py
- consai_examples/consai_examples/game.py
> placement同様に障害物避けるフラグも個別に設定できるように修正

- consai_examples/consai_examples/decisions/attacker.py
ディフェンスエリアにアタッカーが侵入しても、ルール上ファウルは取られないと思いますが、、、念の為対策です。
> ペナルティキックでボールが相手ディフェンスエリアに入ったら、ボールを追いかけない

- consai_robot_controller/src/field_info_parser.cpp
- フィールド外にいるときは壁沿いに避ける
- 壁外に回避位置が生成される場合は壁に直角方向へ避ける
> 壁際における回避アルゴリズムの改善

- consai_examples/consai_examples/control.py
- consai_examples/consai_examples/decisions/attacker.py
- consai_examples/consai_examples/decisions/goalie.py
- consai_examples/consai_examples/field_observer.py
- consai_examples/consai_examples/robot_operator.py
- consai_examples/tests/test_field_observer.py
- consai_robot_controller/src/field_info_parser.cpp
attacker.pyのINPLAY中の処理に相手側のフィールドに入ったとき、shootする、できなければ前方の味方へのパスを検討する処理を追加
どちらもできなければ現行通りにゴールの中心に向けてシュートする
> シュートとパスをattacker.pyに追加

- consai_robot_controller/src/field_info_parser.cpp
RoboDragons ありがとう
https://ssl.robocup.org/wp-content/uploads/2019/01/2014_ETDP_RoboDragons.pdf
> RoboDragonsのキック関数を実装

- consai_examples/consai_examples/decisions/attacker.py
shoot関数ではなくpass関数が使われてたので修正します。
> Attackerがシュート時にキック威力が弱くなる問題を修正

- consai_examples/consai_examples/decisions/attacker.py
- consai_examples/consai_examples/decisions/center_back1.py
- consai_examples/consai_examples/decisions/goalie.py
- consai_examples/consai_examples/operation.py
- consai_examples/tests/test_operation.py
#121 により`Operation`モジュールが追加されました。
この変更をAttaker以外のdecisionにも適用します。
このPRではgoalieとcenter_back1に適用します
> Operationモジュール追加に伴うdecisionsモジュールのリファクタリング

- consai_examples/consai_examples/control.py
- consai_examples/consai_examples/operation.py
- consai_msgs/msg/RobotLocalVelocity.msg
- consai_robot_control_utils/launch/rqt_plot.launch.py
- consai_vision_tracker/src/robot_tracker.cpp
下記の変更を実施します
- robot_local_velocityにnormを追加
- 制御調整用のサンプルをcontrol.pyに追加
- これに伴い、TargetThetaにvalueを追加します。
> 制御テストを簡単にするための更新

- consai_robot_controller/CMakeLists.txt
- consai_robot_controller/include/consai_robot_controller/field_info_parser.hpp
- consai_robot_controller/include/consai_robot_controller/obstacle_ball.hpp
- consai_robot_controller/include/consai_robot_controller/obstacle_environment.hpp
- consai_robot_controller/include/consai_robot_controller/obstacle_robot.hpp
- consai_robot_controller/include/consai_robot_controller/obstacle_typedef.hpp
- consai_robot_controller/include/consai_robot_controller/prohibited_area.hpp
- consai_robot_controller/src/controller_component.cpp
- consai_robot_controller/src/field_info_parser.cpp
- consai_robot_controller/test/field_info_parser_test.cpp
- consai_robot_controller/test/obstacle_environment_test.cpp
consai_robot_controllerに新しい軌道追従関数を導入するためのリファクタリングです。
動作に変更はありませんが、新しいクラスの追加などを実施しています。
- 障害物情報を表現する`obstacle_environment`クラスを追加
- obstacle_environmentを出力する`get_obstacle_environment`関数を追加
- ボールとロボット情報のみ追加しています
- `prohibited_area`を使用した進入禁止エリア情報は追加していません（戦略側のコード変更も必要なため）
- `parse_goal`関数から衝突回避機能を抽出し、`modify_goal_pose_to_avoid_obstacles`関数に移植します
- controller_componentで衝突回避機能をON/OFFしやすくするためです
この変更により、controller_componentの`on_timer_pub_control_command`関数に新しい軌道追従関数を導入できます。
```cpp
void Controller::on_timer_pub_control_command(const unsigned int robot_id)
{
...
if (parser_.parse_goal(
goal_handle_[robot_id]->get_goal(), my_robot, goal_pose, final_goal_pose, kick_power,
dribble_power))
{
// field_info_parserの衝突回避を無効かする場合は、下記の行をコメントアウトすること
goal_pose = parser_.modify_goal_pose_to_avoid_obstacles( …
```
> 新しい軌道追従関数を導入するための下準備

- consai_robot_controller/src/field_info_parser.cpp
ボールキック時の回り込みを修正します。
蹴れないシチュエーションはほとんどなくなりました。
丁寧に動きすぎてる部分もあるので、要調整です。
> ボールキック時の動作を修正

- .github/workflows/build_docker_image.yaml
- .github/workflows/build_lint.yaml
- README.md
> Humbleのみ対応するようにCIを修正

- consai_vision_tracker/src/ball_tracker.cpp
> カルマンフィルタのゲインを1.0→0.1に変更

- consai_robot_controller/src/field_info_parser.cpp
> ボールアプローチ時にボールの方向を向くように変更

- consai_examples/CMakeLists.txt
- consai_examples/consai_examples/operation_test/test_move_to.py
> 動作テスト用のディレクトリ作成と雑巾がけ移植

- consai_examples/CMakeLists.txt
- consai_examples/consai_examples/operation_test/pass_shoot_test.py
コマンド上で以下の変更が可能
- -id0と-id1でロボットのIDで指定できる
- -x0と-y0でid0に指定したロボットの目標座標を変更できる
- -x1と-y1でid1に設定したロボットの目標座標を変更できる
> pass_shootを移植

- .docker/consai-grsim-compose.yml
- .github/workflows/scenario_test.yaml
- tests/test_scenario_kickoff.py
シナリオテストを実行するgithub workfowファイルと、テストファイルを追加します。
ビルド済みのconsai（dockerイメージ）を使用するため、CIのトリガーはmainへのpushのみとします。
テストには、srsslライブラリ（https://github.com/SSL-Roots/simple_robocup_ssl）を使用してます。
> Add CI for scenario test

- .docker/consai-grsim-compose.yml
- .github/workflows/scenario_test.yaml
- tests/test_scenario_kickoff.py
consai_ros2の最新Dockerイメージにコードをマウントし、ビルド＆シナリオテストを実行します。
build_and_lint workflowが成功したときのみシナリオテストを実行します。
> シナリオテストのライブラリを更新　Pull Requestでもシナリオテストを実行する

- .docker/consai-grsim-compose.yml
- .github/workflows/scenario_test.yaml
> Update scenario test workflow

- consai_examples/consai_examples/field_observer.py
#167 と同様の修正です。
https://github.com/SSL-Roots/consai_ros2/issues/159
を一時的に修正します。
ただし、根本的な原因は解決していないため、ソフト構造の変更が必要です。
試合を5分間実施し、エラーが発生しないことを確認しました。
close https://github.com/SSL-Roots/consai_ros2/issues/159
> HotFix, inplay中に落ちる問題を一時的に修正。追加修正。

- .github/workflows/build_lint.yaml
Ref: https://github.com/ros-industrial/industrial_ci/blob/master/doc/industrial_ci_action.yml
> Use cache for industrial ci to speed up.

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .devcontainer/docker-compose.yml
- .dockerignore
- README_devcontainer.md
- consai_web_ui/consai_web_ui/components/RosConnection.tsx
関連するコンテナが自動起動するようにしたり、Readmeを整備したりしました
> Devcontainer (Codespaces)　を快適に利用できるようにした

- consai_robot_controller/src/field_info_parser.cpp
シュート角度しきい値を緩和し、ボールを蹴りやすくします。
これにより、ボールプレースメントのシナリオテストが成功しやすくなります。
> Decrease the difficulty of shoot via chaning angle threthold

- tests/test_scenario_free_kick.py
- tests/test_scenario_penalty.py
- tests/test_scenario_timeout.py
次のシナリオテストを追加します
-  our FREE KICKでtheirゴールにシュートし得点すること
- their FREE KICKでourゴールへのシュートを防ぐこと
- their PENALTYでourゴールへのシュートを防ぐこと
- our TIMEOUTでボールを動かしてもロボットが動かないこと
- their TIMEOUTでボールを動かしてもロボットが動かないこと
> Add scenario tests for free kick, penalty, timeout

- tests/test_scenario_penalty.py
下記のテストを追加します
- their PENALTYで、キーパ以外がボールの後方1m 以上に離れていること
- their PENALTY でキーパがゴールライン上に移動すること
> Add scenario tests for penalty.

- consai_robot_controller/config/control_params.yaml
- consai_robot_controller/include/consai_robot_controller/controller_component.hpp
- consai_robot_controller/include/consai_robot_controller/field_info_parser.hpp
- consai_robot_controller/src/controller_component.cpp
consai_robot_controllerのcontroller_componentをリファクタリングします。
下記については機能変更があります
- stop制御タイマーの廃止：常に100 Hzでコマンドを送信します
- parse失敗による制御停止
> Refactor consai_robot_controller

- consai_examples/launch/start.launch.py
> Set required option for game.py

- consai_robot_controller/src/tactic/tactic_obstacle_avoidance.cpp
> Disable avoid_outside_of_field without ball avoidance

- consai_examples/consai_examples/decisions/attacker.py
- consai_examples/consai_examples/decisions/center_back1.py
- consai_examples/consai_examples/decisions/center_back2.py
- consai_examples/consai_examples/decisions/decision_base.py
- consai_examples/consai_examples/decisions/goalie.py
- consai_examples/consai_examples/decisions/side_wing.py
- consai_examples/consai_examples/decisions/sub_attacker.py
- consai_examples/consai_examples/decisions/zone_defense.py
- consai_examples/consai_examples/game.py
- consai_examples/consai_examples/operation.py
- consai_examples/consai_examples/referee_parser.py
- consai_examples/consai_examples/referee_visualize_parser.py
- consai_examples/consai_examples/robot_control_hasher.py
- consai_examples/consai_examples/robot_operator.py
- consai_msgs/action/RobotControl.action
- consai_robot_controller/include/consai_robot_controller/tactic/tactic_obstacle_avoidance.hpp
- consai_robot_controller/src/field_info_parser.cpp
- consai_robot_controller/src/tactic/tactic_obstacle_avoidance.cpp
衝突回避のフラグをRobotContol.actionに追加し、field_info_parser内でレフェリー情報を直接扱わないようにします。
> Refactor obstacle_avoidance flag usage

- consai_robot_controller/CMakeLists.txt
- consai_robot_controller/include/consai_robot_controller/field_info_parser.hpp
- consai_robot_controller/include/consai_robot_controller/tactic/dribble_tactics.hpp
- consai_robot_controller/include/consai_robot_controller/tactic/tactic_data_set.hpp
- consai_robot_controller/src/field_info_parser.cpp
- consai_robot_controller/src/tactic/dribble_tactics.cpp
- consai_tools/include/consai_tools/geometry_tools.hpp
- consai_tools/src/geometry_tools.cpp
ドリブル処理をDribbleTacticに記述します。
これによりドリブルの前進速度が向上します。
関連して、ボールプレースメントの最後のドリブル速度も早くなります。
Close #140
> Add dribbler tactic

- consai_robot_controller/src/tactic/dribble_tactics.cpp
ドリブルするときに、ボールの周りを回転します。
#212 を解決します。
Close #212
> Rotate around ball at dribble

- consai_robot_controller/src/tactic/dribble_tactics.cpp
- consai_robot_controller/src/tactic/shoot_tactics.cpp
#222 を解決します。
現在の制御パラメータに合わせて、できるだけ無駄のないボールアプローチにしました。
これにより、ボールプレースメントのシナリオテストが成功するはずです。
Close #222
> Fix ball approach

- consai_examples/consai_examples/game.py
STOP GAME以外では通常速度で走行してOKなので、実装を変更します。
Close #209 
AutoReferee でファウルが出ないことを確認してからマージします。
> Disable stop velocity at non STOP signal called.

- consai_examples/consai_examples/decisions/attacker.py
- consai_examples/consai_examples/decisions/goalie.py
- consai_examples/consai_examples/operation.py
- consai_msgs/msg/RobotControlMsg.msg
- consai_robot_controller/include/consai_robot_controller/tactic/tactic_obstacle_avoidance.hpp
- consai_robot_controller/src/field_info_parser.cpp
- consai_robot_controller/src/tactic/tactic_obstacle_avoidance.cpp
- consai_tools/include/consai_tools/geometry_tools.hpp
- consai_tools/src/geometry_tools.cpp
- consai_tools/tests/cpp/test_geometry_tools.cpp
- tests/test_scenario_obstacle_avoidance.py
ディンフェスエリア回避機能を追加します。
ロボットの動作速度や、他の衝突回避に挙動によっては、侵入する可能性があります。
Close #225
> ディフェンスエリア回避の追加

- consai_examples/consai_examples/decisions/attacker.py
- tests/test_scenario_ball_placement.py
ボールプレースメントではディフェンスエリアを回避しません。
Close #234
> disable avoid_defense_area at ball_placement

- consai_examples/consai_examples/decisions/attacker.py
- tests/test_scenario_penalty.py
Our penalty でドリブルしながら前進し、ゴールに近づいたらシュートします。
シュート成功可否を判定するシナリオテストも追加しました。
> Dribbling at our penalty shoot

- consai_examples/consai_examples/decisions/attacker.py
- consai_examples/consai_examples/decisions/center_back.py
- consai_examples/consai_examples/decisions/side_back.py
- consai_examples/consai_examples/decisions/sub_attacker.py
- consai_examples/consai_examples/decisions/zone_defense.py
- consai_robot_controller/src/tactic/shoot_tactics.cpp
ボールプレースメントの待機位置をSTOPゲームと同じにします。
Close #208 
また、ボールプレースメント時にボールに衝突する問題が発生したので、
セットプレイshootの挙動を微調整しました。
> Change ball placement default position to STOP position. Update shoot tactic to pass scenario_test.

- consai_examples/CMakeLists.txt
- consai_examples/consai_examples/game.py
- consai_examples/consai_examples/role_assignment.py
- consai_examples/consai_examples/role_to_visualize_msg.py
- consai_visualizer/src/consai_visualizer/field_widget.py
- consai_visualizer_msgs/CMakeLists.txt
- consai_visualizer_msgs/msg/Objects.msg
- consai_visualizer_msgs/msg/ShapeText.msg
- tests/test_scenario_penalty.py
> Visualize role

- consai_examples/consai_examples/field_observer.py
- consai_examples/consai_examples/game.py
- consai_examples/consai_examples/observer/pass_shoot_observer.py
- consai_examples/tests/test_pass_shoot_observer.py
ゴーリーにパスを出さないように変更しました
field_observerにゴーリーIDの引数追加してそこからパス関数でゴーリーのIDを使うようにしてます
> パス関数でゴーリーにパスをしないように変更

- consai_examples/consai_examples/decisions/side_back.py
- consai_examples/consai_examples/observer/side_back_target_observer.py
相手ロボットとボールの間に入る動作にしていましたが、  
ゴールの間にしました。やりたいのはこっちでした。  
誰も守らない領域があったので、ゾーンとの境目まで担当区域を拡張しました。
> サイドバックの行動修正

- consai_examples/consai_examples/observer/man_mark_observer.py
- consai_examples/consai_examples/observer/side_back_target_observer.py
- consai_examples/consai_examples/observer/zone_man_mark_target_observer.py
- consai_examples/consai_examples/operation_test/control.py
モーションテストを追加します。
実行方法はこちら
```bash
ros2 launch consai_examples start.launch.py game:=false
ros2 run consai_examples control.py --example=1
```
> Add motion_test for control py

- consai_robot_controller/src/tactic/shoot_tactics.cpp
実機ロボットがボールを蹴らない問題を解決したいです。。
Close #256
> Update shoot tactic to go forward at shooting

- consai_examples/consai_examples/decisions/goalie.py
ボールとゴール裏を結ぶ直線上を守るときに、端まで行かないように調整
> ゴーリーのディフェンス位置の調整

- consai_examples/consai_examples/field_observer.py
- consai_robot_controller/include/consai_robot_controller/controller_component.hpp
- consai_robot_controller/src/controller_component.cpp
field_observerにて、ロボットの最終目標位置を取得できるようにします。
decisionからは次のようにデータにアクセスできます。
返り値はboolとState2Dです。
robot_idがデータに存在しない場合は、FalseとState(0, 0, 0）が返ってきます。
```python
result = destination = field_observer.destination_pose(robot_id=0)
```
> Add destination_pose method to field_observer

- consai_examples/consai_examples/decisions/attacker.py
- consai_examples/consai_examples/decisions/decision_base.py
- consai_examples/consai_examples/game.py
- consai_examples/consai_examples/referee_parser.py
#223 の対応
gen_setplay_shoot_function()に実装
> キックオフ時のパスを実装

- consai_examples/consai_examples/decisions/goalie.py
- consai_examples/consai_examples/observer/pass_shoot_observer.py
ボールがディフェンスエリア侵入後になかなか蹴り出さない問題の対応
> ディフェンスエリアにあるボールクリアを以前の動作に戻した

- consai_examples/consai_examples/decisions/attacker.py
タイトル通り
ボール基準でバックパスをするかどうかを決めています
> 自チーム側にボールがあるときはバックパスをしないように変更

- consai_examples/consai_examples/decisions/attacker.py
パスカットしやすい、いきなりシュート打ちにくいなどのメリットがある
tigersのコードを参考にしている
今後はフリーキック全般に適用したい
ボールから0.6m離した位置なので違反取られないかがちょっと心配
> キックオフのときに対角へ移動して相手の邪魔をできるようにした

- consai_examples/consai_examples/decisions/attacker.py
シュートやパスができないとドリブルしていたが、これはオーバードリブルやなかなか蹴り出さない問題があったので変更した
シュートとパスができない場合、相手側のコーナーへ蹴る
> アタッカーの行動生成の方法をフラグで管理

- consai_robot_controller/config/control_params.yaml
> デフォルトの加速度を変更

- .docker/consai-grsim-compose.yml
- .github/workflows/build_docker_image_for_ci.yaml
- .github/workflows/scenario_test.yaml
- tests/test_scenario_ball_placement.py
#305 の動作検証です。
PRでシナリオテストが実行されるかを確認します、
> CI Trigger test

- .docker/consai-grsim-compose.yml
- .github/workflows/build_docker_image_for_ci.yaml
- .github/workflows/build_lint.yaml
- .github/workflows/scenario_test.yaml
Dockerイメージ名をconsai_ros2に統一し、タグで種類を分けることにします。
- humble: GUI入りのDocker イメージ
- humble-light: GUI無し
- humble-light-sha-***: シナリオテスト用
それに伴い、workflowファイルなどを修正します。
> Update workflow files with new docker image name.

- .github/workflows/build_docker_image_for_ci.yaml
- .github/workflows/scenario_test.yaml
CIで実行するシナリオテストを、matrix envによる複数ジョブに分割します。
これにより、テスト再実行時間の短縮を狙います。
テストの合計実行は増えるかも知れません。
> Separete scenario tests to multiple jobs

- .github/workflows/scenario_test.yaml
シナリオテストに失敗してもログが出力さなくなったので修正します。
> Fix to upload scenario test artifact

- .github/workflows/scenario_test.yaml
Matrix CIでアーティファクトのアップロードに失敗していたので修正します。
下記PRで修正完了したことを確認しています。
https://github.com/SSL-Roots/consai_ros2/pull/312
> Fix ci to upload artifacts with matrix

- consai_robot_controller/src/tactic/shoot_tactics.cpp
- consai_tools/include/consai_tools/geometry_tools.hpp
- consai_tools/src/geometry_tools.cpp
> ボールアプローチに速度を考慮

- consai_game/consai_game/play/conditions/ball_conditions.py
- consai_game/consai_game/play/factory/blank_plays.py
- consai_game/consai_game/utils/geometry.py
> Implement play_condition with arg example

- consai_game/consai_game/utils/geometry.py
- consai_game/consai_game/world_model/field_model.py
- consai_game/consai_game/world_model/world_model.py
- consai_game/consai_game/world_model/world_model_provider_node.py
- world_modelに`field`と`field_points`を追加します
- utils/geometryに`Point`と`Rectangle`を追加します
```python
print(world_model.field.length)  # 12.0
print(world_model.field.width)  # 9.0
print(world_model.field_points.our_defense_are.top_left)  # Point(x=-6.0, y=1.8)
```
> Add field_model

- consai_game/consai_game/core/play/play_node.py
- consai_game/consai_game/core/role_assignment/assignor.py
- consai_game/consai_game/core/role_assignment/methods/base.py
- consai_game/consai_game/core/role_assignment/methods/by_id.py
- consai_game/consai_game/core/role_assignment/methods/by_visible.py
- consai_game/consai_game/main.py
- consai_game/launch/start.launch
ロールアサインがgoalie idに対応します
Role[0] をgoalieとしています。
次のコマンドを実行して、指定したIDがgoalieとしてアサインされることを確認しました。
```sh
ros2 launch consai_game start.launch goalie:=3
```
> Support goalie id in role assignment

- consai_game/consai_game/play/books/playbook_default.py
- consai_game/consai_game/play/factory/simple_plays.py
blank_playsをsimple_playsに変更します
> Rename blank_plays to simple_plays

- consai_game/consai_game/world_model/ball_position_model.py
https://github.com/orgs/SSL-Roots/projects/7/views/1?pane=issue&itemId=106159446
出た入った両方に同じヒステリシスのしきい値を入れています
どちらかだけでよければ調整します。
> ボールポジション判定にヒステリシス追加

- consai_game/consai_game/play/books/playbook_default.py
- consai_game/consai_game/play/conditions/referee_conditions.py
- consai_game/consai_game/play/factory/simple_plays.py
- consai_game/consai_game/world_model/referee_model.py
FREE_KICKやNORMAL STARTなどでアクション時間が経過したあとにRUNNING Playへ遷移します。
KICK OFF -> NORMAL STARTで10秒経過したあとRUNNINGに遷移することを確認しました。
FREE KICK の5秒後にRUNNINGへ遷移することを確認しました
> Add a running play.

- consai_game/consai_game/play/books/playbook_default.py
- consai_game/consai_game/play/conditions/ball_conditions.py
- consai_game/consai_game/play/factory/running_plays.py
- consai_game/consai_game/play/factory/simple_plays.py
ボールがディンフェスエリアにあるかどうかでrunning のPlayを切り替えます。
Role0またはRole1がボールを蹴るようにします。
またrunning playにあわせるため、stopとforceも微修正してます。
> Add conditions and plays that use ball_is_in_defense_area method.

- .github/workflows/build_docker_image.yaml
- .github/workflows/build_docker_image_for_ci.yaml
- .github/workflows/build_lint.yaml
- .github/workflows/scenario_test.yaml
連続pushされたときにActionを止めるべく，workflowに設定を追加
チケット：https://github.com/orgs/SSL-Roots/projects/7/views/1?pane=issue&itemId=105177725
> concurrencyの設定を追加

- consai_game/consai_game/tactic/avoid_ball.py
- consai_game/consai_game/tactic/slow_safe_position.py
チケット：https://github.com/orgs/SSL-Roots/projects/7/views/1?pane=issue&itemId=106361884
ボールをよけてゆっくりうごくよ
simple_playのstop()の中身を変更して確認できるよ
```
from consai_game.tactic.avoid_ball import SlowSafePosition
```
```
[SlowSafePosition(-6.0, 0.0)],
[SlowSafePosition(-3.0, 3.0)],
[SlowSafePosition(-3.0, 2.0)],
[SlowSafePosition(-3.0, 1.0)],
[SlowSafePosition(-3.0, 0.0)],
[SlowSafePosition(-3.0, -1.0)],
[SlowSafePosition(-3.0, -2.0)],
[SlowSafePosition(-3.0, -3.0)],
[SlowSafePosition(-2.0, 1.0)],
[SlowSafePosition(-2.0, 0.0)],
[SlowSafePosition(-2.0, -1.0)],
```
> SlowSafePosition追加

- consai_robot_controller/include/consai_robot_controller/tactic/tactic_obstacle_avoidance.hpp
- consai_robot_controller/src/field_info_parser.cpp
- consai_robot_controller/src/tactic/tactic_obstacle_avoidance.cpp
> Avoid defense area

- consai_game/consai_game/play/factory/simple_plays.py
- consai_game/consai_game/tactic/slow_safe_position.py
STOP GAMEでボールを回避します。
stop_gameのシナリオテストをパスすることを確認しました
> Avoid ball at stop game

- consai_robot_controller/src/controller_component.cpp
controller_component.cppに条件分岐を追加
`command.mode == MotionCommand::MODE_NAVI`では`modify_goal_pose_to_avoid_obstacles()`を実行していたが，`command.mode == MotionCommand::MODE_DIRECT_POSE`では`modify_goal_pose_to_avoid_obstacles()`を実行しない
> MODE_DIRECT_POSEの処理を追加

- consai_game/consai_game/world_model/ball_activity_model.py
- consai_game/consai_game/world_model/world_model.py
- consai_game/consai_game/world_model/world_model_provider_node.py
- consai_tools/consai_tools/geometry/geometry_tools.py
- world_modelに`BallActivityModel`を追加します
- geometry_toolsに`get_norm`を追加します
```python
world_model.ball_activity.ball_state  # ボールの状態
world_model.ball_activity.ball_holder  # ボールを持っているロボット情報
world_model.ball_activity.ball_is_moving  # ボールが動いているか
```
新規model追加のため、他のコードには影響なしです
> Add ball_activity_model

- consai_game/consai_game/world_model/game_config_model.py
- consai_game/consai_game/world_model/world_model.py
- consai_game/consai_game/world_model/world_model_provider_node.py
game_config_modelを作り、ゴーリーIDと、is_yellowを格納しました。
リファクタリングなので、他への影響なしです
> Add game_config_model

- consai_game/consai_game/world_model/visualize_msg_publisher_node.py
> Visualize ball activity

- consai_game/consai_game/tactic/chase_ball.py
> ボールを追いかけるtacticを追加

- consai_game/consai_game/tactic/dribble.py
Shootを参考に作成
神のハイパーパラメータがいくつかあるが，一旦動作を見てほしい気持ちがあふれる
> DribbleのTacticを追加

- consai_game/consai_game/main.py
- consai_game/consai_game/world_model/robot_activity_model.py
- consai_game/consai_game/world_model/world_model_provider_node.py
ボールに近い順のロボットリストをrobot_activity_modelに追加します
> Add robots_by_ball_distance to robot_activity_model

- consai_game/consai_game/tactic/kick/shoot.py
- consai_game/consai_game/world_model/kick_target_model.py
チケットhttps://github.com/orgs/SSL-Roots/projects/7?pane=issue&itemId=107440743
- パス成功率ランキングを追加しました
- 追加の際にshootと混同しそうな命名があった変数を解明しています
- 成功率の処理は実装が甘いので別途修正が必要
- 現在の状態だとパスするのにかなり厳しいような気がしてます
> Add Pass success rate ranking

- consai_game/consai_game/world_model/visualize_msg_publisher_node.py
> Visualize pass targets

- consai_game/consai_game/tactic/kick/kick.py
- consai_game/consai_game/tactic/kick/shoot.py
パスとシュートで同じ動きを実施するため、Kickという抽象的なTacticを追加します。
コンストラクタの引数か、変数`target_pos`にセットされた目標位置に向かってボールを蹴ります。
パスの場合はキック威力を調整したいですが、まだ対応していません。
> Add simple kick tactic

- consai_game/consai_game/play/factory/simple_plays.py
- consai_game/consai_game/tactic/wrapper/wrapper_look_ball.py
ボールを見るようにcommandを上書きするWrapperTacticを追加します。
次のように使用します
```python
WrapperLookBall(Position(-3.0, 2.0)
```
> Add wrapper_look_ball

- consai_game/consai_game/world_model/game_config_model.py
- consai_game/consai_game/world_model/world_model_provider_node.py
game_config_modelにロボットの最大速度と加速度を追加します。
> Add max vel and acc to game_config

- consai_game/consai_game/core/tactic/agent.py
- consai_game/consai_game/tactic/composite/composite_offense.py
- consai_game/consai_game/tactic/kick/kick.py
ボールをコツコツ蹴ってドリブルするオプションをkick tacticに追加しました。
また、ロボットをON/OFFしたときにout of indexエラーが発生してたので修正します。
Agentで、ロボットIDが存在しなければtacticを実行しない　としたことで解決です。
force_startで、パスモシュートもできないときに、ボールを蹴ってドリブルします。
tappingするときに、ボール近くでロボットが止まることがあります。
これは、kick動作を改善すれば解決するはずです。
> Add tapping kick.

- consai_game/consai_game/play/books/playbook_swab.py
- consai_game/consai_game/play/factory/swab_plays.py
- consai_game/consai_game/tactic/swab.py
- consai_game/consai_game/world_model/robot_activity_model.py
- consai_game/consai_game/world_model/world_model_provider_node.py
- setup.cfg
チケット：https://github.com/orgs/SSL-Roots/projects/7/views/1?pane=issue&itemId=106150596
- GC必須
- HALTで停止
- STOPでx軸を往復
- ロボット台数が少なくても動作する
- 途中でロボットを投入すると，目標位置へ到達後動かなくなるバグがある
> 雑巾がけのplayを追加

- consai_game/consai_game/tactic/receive.py
チケット：https://github.com/orgs/SSL-Roots/projects/7/views/1?pane=issue&itemId=108097275
そもそもの算出方法を一次関数の交点ではなく，Transを利用するようにした
> 位置の算出はTransを使うように変更（0割が発生しないように対応）

- consai_game/consai_game/world_model/world_meta_model.py
- consai_game/consai_game/world_model/world_model.py
- consai_game/consai_game/world_model/world_model_provider_node.py
メタ情報のモデルを追加します。
- update_rate: 更新周期 Hz
- update_counter: world_model_provider_nodeのupdateを実行するたびにカウントアップします
> Add world_meta_model

- consai_game/consai_game/play/conditions/debug_conditions.py
- consai_game/consai_game/play/factory/swab_plays.py
チケット：https://github.com/orgs/SSL-Roots/projects/7/views/1?pane=issue&itemId=108058891
> デバッグ用にtrue/falseを返すconditionを追加し，雑巾がけでも利用するように変更

- .github/workflows/build_lint.yaml
- .gitignore
- consai_game/consai_game/tactic/dribble.py
- consai_game/consai_game/tactic/kick/kick.py
- consai_game/consai_game/tactic/swab.py
- consai_game/consai_game/utils/make_graph_state_machine.py
- consai_game/package.xml
- consai_robot_controller/CMakeLists.txt
- consai_robot_controller/launch/controller.launch.py
- setup.cfg
- チケット：https://github.com/orgs/SSL-Roots/projects/7/views/1?pane=issue&itemId=106219160
- 以下のパッケージが必要
```bash
$ sudo apt install graphviz graphviz-dev
$ pip install pygraphviz
```
- 実行
```python
$ cd ~/ros2_ws/src/consai_ros2/consai_game/consai_game/utils
$ python3 make_graph_state_machine.py
```
> State Machineをグラフで保存するプログラムを作成

- consai_game/consai_game/play/factory/simple_plays.py
- consai_game/consai_game/tactic/composite/composite_ball_placement.py
- consai_game/consai_game/tactic/stay.py
- consai_game/consai_game/tactic/wrapper/forbid_moving_in_placement_area.py
- consai_game/consai_game/world_model/ball_activity_model.py
- consai_game/consai_game/world_model/kick_target_model.py
- consai_game/consai_game/world_model/robot_activity_model.py
- consai_game/consai_game/world_model/world_model_provider_node.py
ボールプレースメント機能を実装します
また、kick_targetの計算でout of index errorが出るのを修正します
ボールプレースメント専用のCompositeTacticです。
自チームのボールプレースメント時に、全エージェントにアサインしてください
制御が効いたStop Tacticです。
ロボットは脱力していますが、進入禁止エリア回避を有効にできます
プレースメントエリア回避を有効にするWrapper Tacticです。
> Implement ball_placement. Fix out of index error in kick_target.

- consai_game/consai_game/play/factory/simple_plays.py
- consai_game/consai_game/tactic/ball_clear.py
チケット：https://github.com/orgs/SSL-Roots/projects/7?pane=issue&itemId=108331916
ノーマルスタートの動作も追加した
> ゴーリーにボールクリアの動作を追加

- consai_game/consai_game/tactic/center_back.py
> センターバックが制限を超えないように

- consai_game/consai_game/play/books/playbook_default.py
- consai_game/consai_game/play/conditions/referee_conditions.py
- consai_game/consai_game/play/factory/simple_plays.py
- consai_game/consai_game/world_model/referee_model.py
- consai_game/consai_game/world_model/world_model_provider_node.py
キックオフとフリーキックでボールが動いたらrunningに切り替わります
また、force_startを廃止してrunningに統合します。
さらに、Playファイルにある不要なPlay（force_start、normal_start、goal）を削除します。
> Switch to running when ball moved at setplay.

- consai_game/consai_game/tactic/position.py
- consai_game/consai_game/utils/adjust_position_to_field.py
- consai_robot_controller/include/consai_robot_controller/tactic/tactic_obstacle_avoidance.hpp
- consai_robot_controller/src/field_info_parser.cpp
- consai_robot_controller/src/tactic/tactic_obstacle_avoidance.cpp
consai_descriptionでfiledサイズを変更してもgameが動くようにします。
utilsにAdjustPositionというクラスメソッドを追加しました。
内部にDivision Aのフィールドサイズを持っています。
新しく設定されたフィールドと、div Aフィールドとの比率で位置情報x, yを変換します
tactic_obstacle_avoidanceがフィールドサイズ変更に対応します。
boundary_width = 0.3は未対応です。（そもそもパラメータを用意してないため）
> Support filed size changing.

- consai_game/consai_game/tactic/ball_approach.py
- consai_game/consai_game/tactic/dribble.py
- consai_game/consai_game/world_model/ball_activity_model.py
チケット：https://github.com/orgs/SSL-Roots/projects/7/views/1?pane=issue&itemId=108354432
実機で検証する
> ボールアプローチの追加とdribbleでの利用

- auto_restart.sh
しました。
Tracebackを追いかけるだけなので本当にこれだけでいいのかちょっと不安です
ros2_ws上で
```
./src/consai_ros2/auto_restart.sh
```
これで動くはず
> 自動再起動用シェルスクリプト追加

- consai_description/config/strategy/normal.yaml
- consai_game/consai_game/world_model/ball_activity_model.py
- consai_game/consai_game/world_model/game_config_model.py
- consai_game/consai_game/world_model/visualize_msg_publisher_node.py
- consai_game/consai_game/world_model/world_model_provider_node.py
- consai_tools/CMakeLists.txt
- consai_tools/consai_tools/geometry/geometry_tools.py
- consai_tools/tests/test_geometry_tools.py
ボールが相手のゴールに入るかを判定します。
`ball_activity.ball_stop_position` : ボールの到着位置
`ball_activity.ball_will_enter_thier_goal` : ボールが相手のゴールに入る場合はTrue
ボールの到着位置は摩擦係数とボール速度を使って計算します。
これらのパラメータはconsai_descriptionのstrategy/normal.yamlで変更できます
ボールの到着位置を描画します
ボールがゴールに入る場合は塗りつぶされます
> Predict ball will enter the their goal.

- consai_game/consai_game/tactic/composite/composite_offense.py
CompositOffenseの更新です。
ボールが相手のゴールに入る場合は、desirede_poseを調整してボールを回避します。
> CompositOffense avoids our shoot when the ball will enter the goal.

- consai_game/consai_game/play/conditions/ball_conditions.py
チケット：https://github.com/orgs/SSL-Roots/projects/7/views/1?pane=issue&itemId=108674770
> ボールがどっち側にあるか返すconditionを追加

- consai_game/consai_game/tactic/kick/kick.py
Kick Tacticで、ボールをける前にぶつかってしまう問題を解決します。
また、状態遷移の判定をシンプルにしています。
> Fix kick tactic

- consai_game/consai_game/play/conditions/ball_conditions.py
- consai_game/consai_game/world_model/ball_activity_model.py
チケット：https://github.com/orgs/SSL-Roots/projects/7/views/1?pane=issue&itemId=108674875
> ボールを保持チームのconditionを追加

- consai_game/consai_game/core/role_assignment/methods/by_cost.py
- consai_game/consai_game/core/role_assignment/methods/by_visible.py
- consai_game/consai_game/core/role_assignment/methods/fill_role_gaps.py
- consai_game/launch/start.launch
ロールアサインを位置ベースにします。
ロボットの移動コストが最小になるようにロールアサインします。
これまで通り、role[0]がゴーリ、role[1]が最も優先度が高いロールです。
> Default to position cost role assignment

- consai_game/consai_game/play/factory/running_plays.py
- consai_game/consai_game/play/factory/simple_plays.py
- consai_game/consai_game/tactic/composite/composite_goalie.py
- consai_game/consai_game/tactic/defend_goal.py
- consai_game/consai_game/tactic/goalie_positioning.py
チケット：https://github.com/orgs/SSL-Roots/projects/7/views/1?pane=issue&itemId=108791222
> composite_goalieの追加とそれに伴う各ファイルの変更

- consai_game/consai_game/core/role_assignment/methods/by_cost.py
- consai_game/consai_game/tactic/center_back.py
- consai_game/consai_game/tactic/composite/chase_or_position.py
- consai_game/consai_game/tactic/composite/composite_ball_placement.py
- consai_game/consai_game/tactic/composite/composite_defense.py
- consai_game/consai_game/tactic/composite/composite_man_mark.py
- consai_game/consai_game/tactic/composite/composite_offense.py
> ボールの移動地点を守るように修正

- consai_game/consai_game/play/factory/simple_plays.py
チケット：https://github.com/orgs/SSL-Roots/projects/7/views/1?pane=issue&itemId=108798159
ゴーリーもポジションをセットしている
> 自ペナルティのときゴーリーもボールを蹴る対象に変更

- consai_game/consai_game/play/factory/simple_plays.py
- consai_game/consai_game/tactic/man_mark.py
> マンマークの位置がペナルティエリアに入らないように＆相手のプレースメント中のゴーリーがペナルティエリアから出ないように

- consai_game/consai_game/world_model/visualize_msg_publisher_node.py
- consai_game/consai_game/world_model/world_model_provider_node.py
world_modelの情報の更新タイミングが、update()と、callbackで一致しないため、エラーが発生していました。
callbackではメンバ変数の更新飲みを実施し、update()ないだけでworld_modelを更新するように修正します
また、デバッグ用にworld_modelの更新時間を計測します。後で消します。
> Fix out of index error.

- consai_description/config/strategy/normal.yaml
2025年大会会場のフィールドに合わせてボールの摩擦係数を変更しました
> ボールの摩擦係数の値を変更

- consai_game/consai_game/tactic/kick/kick.py
kickingの際のdistanceを0.1→0.08に変更しました
> ロボットの到達目標位置をボールのやや前方に変更

- consai_game/consai_game/world_model/kick_target_model.py
チケットhttps://github.com/orgs/SSL-Roots/projects/7/views/1?pane=issue&itemId=108941770
> Fix shoot score method

- consai_game/consai_game/tactic/back_dribble.py
- consai_game/consai_game/tactic/composite/composite_ball_placement.py
バックトリブルをボールプレースメントで使います。
フィールド外にボールが出たときに、バックドリブルします。
ボールを扱うロボットの交代合戦はまだ残ってます。
> Use back_dribble for ball placement.

- consai_game/consai_game/tactic/ball_clear.py
- consai_game/consai_game/tactic/composite/composite_goalie.py
- consai_game/consai_game/tactic/kick/shoot.py
チケット1：https://github.com/orgs/SSL-Roots/projects/7/views/1?pane=issue&itemId=108882008
チケット2：https://github.com/orgs/SSL-Roots/projects/7/views/1?pane=issue&itemId=108949061
ディフェンスエリアにあるときにボールの速度を見ていたが，やめました
> ボールクリア時の動作を変更

- consai_tools/CMakeLists.txt
- consai_tools/consai_tools/hysteresis/hysteresis.py
- consai_tools/tests/test_hysteresis.py
consai_toolsにヒステリシス計算用のモジュールを追加します。
使い方はテストコードを見てください！
> Add hysteresis module to consai_tools

- consai_game/consai_game/tactic/ball_clear.py
- consai_game/consai_game/tactic/composite/composite_offense.py
- consai_game/consai_game/tactic/kick/kick.py
- consai_game/consai_game/world_model/kick_target_model.py
final_target_posを追加して、target_posを固定するようにした
ベストパス相手の切り替え処理を一旦無効化した
> キックターゲットの切り替わりまくり問題を対応

- consai_game/consai_game/tactic/back_dribble.py
- consai_game/consai_game/tactic/dribble.py
- consai_vision_tracker/src/ball_tracker.cpp
ボールプレースメント時のドリブル動作を安定化させます。
ゆっくりボールに近づき、ゆっくりフィールド端から離れます
走行速度を早くします。
目的地に近づくほどゆっくり動きます。
ボールの消失には対応してません。
consai_vision_trackerでボールのvisibilityを操作するように戻しました。
ボールが消えてしまうので、いろいろ影響が出るかもしれません。。。
（たぶん、みんなball.is_visibleを使ってないので、大丈夫だと思うけど）
> Update ball placement for dribbling

- consai_game/consai_game/tactic/ball_clear.py
- consai_game/consai_game/tactic/composite/composite_goalie.py
- consai_game/consai_game/tactic/defend_goal.py
- consai_game/consai_game/tactic/kick/kick.py
チケット
https://github.com/orgs/SSL-Roots/projects/7/views/1?filterQuery=assignee%3Auchikun2493&pane=issue&itemId=108955318
https://github.com/orgs/SSL-Roots/projects/7/views/1?filterQuery=assignee%3Auchikun2493&pane=issue&itemId=108955345
ボールクリアに関して，パスを削除し，(x=0.0, y=3.5)か(x=0.0, y=-3.5)に蹴る
> ボールクリアからパスを削除，ゴール回避位置の調整

- consai_game/consai_game/tactic/chase_ball.py
Chaseballでのchase_distanceを0.8に変更しました
> セットプレイのときにボールから0.8m離れるよう変更

- consai_game/consai_game/tactic/kick/kick.py
https://github.com/orgs/SSL-Roots/projects/7/views/1?pane=issue&itemId=108956189
> kick_tacticでのkicking時のdistanceを0.04に変更

- consai_description/config/rule/division_a.yaml
- consai_game/consai_game/tactic/composite/composite_goalie.py
- consai_msgs/msg/NaviOptions.msg
- consai_robot_controller/include/consai_robot_controller/tactic/tactic_obstacle_avoidance.hpp
- consai_robot_controller/src/field_info_parser.cpp
- consai_robot_controller/src/tactic/tactic_obstacle_avoidance.cpp
ゴール回避を追加しました。
自チームのゴールのみを回避します。
ゴーリーのtactic内で行っている衝突回避が不要になるので、別途取り除いてください。
> Implement avoid goal

- consai_game/consai_game/tactic/composite/composite_offense.py
チケット：https://github.com/orgs/SSL-Roots/projects/7/views/1?pane=issue&itemId=108988120
ここではスコアの算出ではなく，閾値のみの対応
> 実際の試合に合わせてシュート閾値を変更

- consai_game/consai_game/tactic/composite/composite_ball_placement.py
- consai_game/consai_game/world_model/ball_activity_model.py
- consai_game/consai_game/world_model/referee_model.py
ボールがずっと見えない状態であっても、フィールド内にはいっていそうなタイミングで処理を切り替える
ボール見えていないときの到着判定を追加しました
> プレースメントのバックドリブル判定にダミーボールの場所の考慮も追加

- consai_game/consai_game/play/factory/simple_plays.py
- consai_game/consai_game/tactic/composite/composite_offense.py
- consai_game/consai_game/tactic/kick/kick.py
ボールが消えてもキックできるように、ダミーボールをキックに使います。
また、セットプレイでの走行速度を遅くします。
また、is_setplayをデフォルトfalseにします。　CompositeDefenseなどでもkickを使ってるので。
> Use dummy_ball for kicking. is_setplay default to false.

- consai_game/consai_game/tactic/composite/composite_offense.py
- consai_game/consai_game/tactic/kick/kick.py
- consai_game/consai_game/tactic/steal_ball.py
相手のボールを奪う動作をkick tacticから抽出して、compositeに組み合わせます。
> Extract steal ball code from kick tactic

- consai_game/consai_game/tactic/composite/composite_ball_placement.py
- consai_game/consai_game/tactic/move_to_ball.py
ナビオプションの変更と
目標位置がフィールド内になるように修正
> プレースメント後、ロボットがフィールド外にいたときのボールの避け方を変更

- consai_game/consai_game/tactic/kick/kick.py
インプレイのキックを改善します。
- ボールに近づくとき、ターゲットを見るようにして、無駄な旋回を減らします
- is_on_kick_lineのしきい値をゆるくして、ボールに近づきやすくします
- デメリットとして、肩でボールを押すことがあります。
> Update inplay kick

- consai_game/consai_game/tactic/composite/composite_offense.py
CompositeOffense内で情報を共有するための仕組みを追加します。
動作としては変化無しです。
> Add shared_info to CompositeOffense

- consai_game/consai_game/tactic/composite/composite_offense.py
- consai_game/consai_game/world_model/robot_activity_model.py
> Revert Feature/new receive approach (#485)

- auto_restart.sh
チケット: https://github.com/orgs/SSL-Roots/projects/7/views/1?pane=issue&itemId=109009119
環境変数を設定して起動できるようにした
```bash
$ export CONSAI_COLOR="yellow"  # または "blue"。yellow:=true は yellowとする
$ export CONSAI_SIDE="right" # または"left"。 invert:=true は rightとする
$ ./auto_restart.sh
```
> auto_restar.shに環境変数を追加
