consai_examples/README.md, consai_examples/consai_examples/game.py, consai_examples/consai_examples/role_assignment.py, consai_examples/launch/start.launch.py
start.launch.pyに引数`game:=true`を与えることでgame.pyも一緒に起動できるようになりました。
コマンド数が減ってうれしいですね。
`yellow`、`invert`、`goalie`オプションにも対応してます。
また、CON-SAI vs CON-SAIを実行するためのドキュメントを追加してます。
consai_examplesのREADMEを確認してください。
=> start.launch.pyからgame.pyを起動できる

consai_robot_controller/src/field_info_parser.cpp
start.launch.py 起動時にcontroller側のノードが落ちることを修正します。
ただし、レフェリー信号が変更されるまで一部のロボットが動かないという問題が出ました。
こちらはgame.py側で対策を考えます。
=> controllerにて起動時にgeometryリソースがないのに参照していたところを修正

consai_vision_tracker/src/robot_tracker.cpp
ロボット座標の存在度を示す`visibility`のデフォルト値を、1.0から0.0に変更します。
これにより、CON-SAI起動直後の状態が、
「すべてのロボットが座標0, 0に存在する」　から
「ロボットが1台もいない」　に変わります。
game.py起動時の意図しないアタッカー入れ替わりを防ぐことができます。　が
その他、どのような影響が出るのかは未検証です。
=> 起動時のロボットのvisibilityを0.0に変更し、ロボットは存在しない状態からスタートさせる

consai_examples/CMakeLists.txt, consai_examples/consai_examples/control.py, consai_examples/consai_examples/decisions/substitute.py, consai_examples/consai_examples/game.py, consai_examples/consai_examples/robot_operator.py, consai_examples/tests/test_robot_operator.py, consai_msgs/CMakeLists.txt, consai_msgs/msg/ConstraintObject.msg, consai_msgs/msg/NamedTargets.msg, consai_robot_controller/include/consai_robot_controller/controller_component.hpp, consai_robot_controller/include/consai_robot_controller/field_info_parser.hpp, consai_robot_controller/src/controller_component.cpp, consai_robot_controller/src/field_info_parser.cpp, consai_visualizer/src/consai_visualizer/field_widget.py, consai_visualizer/src/consai_visualizer/visualizer.py
robot_operatorとコントローラ間で使用するメッセージ（`ConstraintObject`）に、名前付きターゲット（`NamedTargets`）を追加します。
NamedTargetsは`named_targets`トピックとしてpub/subします。
NamedTargetsは、ボールやロボットと同じようなオブジェクトとしてコントローラが参照できます。
- NamedTargets型を追加します
- ConstraintObjectのtypeに`NAME_TARGET`を追加します。
- NamedTargetを描画します
- `named_targets`トピックをsubscribeします
- `ConstraintObject`のtype`NAME_TARGET`に対応します
- NamedTargetを扱うための、set, remove, clear, publish関数を追加します
- これらは`test_robot_operator.py`でユニットテストしています
- NamedTargetを使用した関数`move_to_named_target`と` move_to_named_target_with_reflect_pass_to_named_target`を追加します
- **これらはあくまで一例です**
- 今後の開発で、必要に応じて便利な関数を追加してください（例：NamedTargetに向かってシュートする関数）
- NamedTargetの使用例として、`test_use_named_targets`と`test_star_pass`を追加します
- `test_star_pass`は5台のロボットが互いにパスする関数ですが、**パスできません**
- …
=> NamedTargetを追加し、動的に変更できる任意座標を、行動の目標値として使用できる

consai_robot_controller/src/field_info_parser.cpp
field_info_parser.cppに避ける位置生成を新たに追加
- 回避対象ロボットと障害物の距離が0.5mの場合を追加
- 相対位置座標系から見て0.5 * 1.2 = 0.75m横に回避位置を生成
- それ以外の場合はこれまで通り
- 相対位置座標系から見て0.2m奥，0.5m横に回避位置を生成
=> 障害物と距離が近い場合の回避行動を追加

consai_examples/CMakeLists.txt, consai_examples/consai_examples/geometry_tools.py, consai_examples/tests/test_geometry_tools.py
consai2に実装されていたtransクラス（といくつかの関数）を移植
- geometry_tools.py
- consai2のtool.pyの移植版
- consai2ではPose2()を座標に使っていたが今回はリストで実装
- test_geometry_tools.py
- geometry_tools.pyのテストコード
=> Transクラスの実装とテストの作成

consai_examples/consai_examples/control.py, consai_examples/consai_examples/field_observer.py
- field_observer.py
- パス関数で使っているフィールドにいるロボットの抽出とボールを保持しているロボットから見た味方、相手ロボットのIDをリストに格納している部分を関数化
- control.py
- パス関数移植前の動作確認用コードの削除
=> フィールドにいるロボットの抽出とボールを保持しているロボットから見た味方、相手ロボットのIDをリストに格納している部分の関数化

consai_msgs/CMakeLists.txt, consai_msgs/msg/RobotLocalVelocities.msg, consai_msgs/msg/RobotLocalVelocity.msg, consai_msgs/package.xml, consai_vision_tracker/CMakeLists.txt, consai_vision_tracker/include/consai_vision_tracker/robot_tracker.hpp, consai_vision_tracker/include/consai_vision_tracker/tracker_component.hpp, consai_vision_tracker/package.xml, consai_vision_tracker/src/robot_tracker.cpp, consai_vision_tracker/src/tracker_component.cpp
ロボット走行制御をデバッグするため、ロボット座標系からみたロボット速度を`robot_local_velocities`というトピックでpublishします。
デバッグ用のため、戦略や制御ではこのトピックを使用しません。
ロボットから見て、前後方向をX軸、左右方向をY軸として走行速度を変換してます。
start.launch.pyにて、`invert:=True`にしても問題なく速度を出力することを確認しています。
=> ロボット座標系から見たロボット速度をrobot_local_velocitiesトピックとしてpublishする

consai_examples/launch/start.launch.py, consai_robot_controller/launch/test.launch.py
start.launch.py実行時に、visionとrefereeのマルチキャストアドレス、ポートを変更できます
使用例：
```sh
$ ros2 launch consai_examples start.launch.py vision_addr:=224.5.23.9 vision_port:=10021
$ ros2 launch consai_examples start.launch.py referee_addr:=224.5.23.12 referee_port:=10004
```
=> start.launch.pyにvisionとrefereeのaddr, port引数追加

consai_examples/consai_examples/decisions/attacker.py, consai_examples/consai_examples/field_observer.py, consai_examples/consai_examples/game.py
- ボール場外判定を細分化（4パターン）
- x方向に前後
- y方向に左右
- アタッカーがボール追いかけない判定にボール場外フラグ追加（前後）
- 相手のゴールの中や、ゴール裏にボールがあっても追いかけようとするためそれを防ぐ
- 場外左右のときのアタッカーの動きは特に修正していません
=> ボールの場外判定を前後左右それぞれ判定するようにした

consai_visualizer/resource/visualizer.ui, consai_visualizer/src/consai_visualizer/field_widget.py, consai_visualizer/src/consai_visualizer/visualizer.py
ロボットの消失・追加をデバッグするための機能追加です。
Visualizer下部にロボットのgrSimのロボットをON/OFFできるボタンを追加します。
https://user-images.githubusercontent.com/18494952/235544650-afbfd3b3-9b31-4ec3-b363-3583ae592a7a.mp4
=> grSimのロボットをON/OFFできるボタンをVisualizerに追加

consai_robot_controller/src/field_info_parser.cpp
> #66 の改善
> 
> - ボールが進路上にあるか判定
>   - Trans後のy座標で判定
> - 進路上にあれば回避
>   - まだ少し不安定さはあるがかなり改善された
元々上記のような対応だったが，通常の回避行動を改善にした
STOP中のボール回避はavoid_ball_500mm()で生成することにした
=> 回避アルゴリズムの改善

consai_examples/consai_examples/decisions/attacker.py, consai_examples/consai_examples/decisions/center_back1.py, consai_examples/consai_examples/decisions/center_back2.py, consai_examples/consai_examples/decisions/decision_base.py, consai_examples/consai_examples/decisions/side_back1.py, consai_examples/consai_examples/decisions/side_back2.py, consai_examples/consai_examples/decisions/sub_attacker.py, consai_examples/consai_examples/decisions/zone_defense.py
ペナルティキック終了後、各ロボットが持ち場に戻るとき、ディフェンスエリアに侵入することがありました。
ペナルティキックでの待機位置を変更して、侵入を防ぎます。
- 試合を再開する前の、停止、フリーキックの間、すべてのロボットは相手のディフェンスエリアから少なくとも0.2m以上離れていなければならない。
- ロボットが相手ディフェンスエリアから離れるため、2秒間の猶予が設けられる。
=> ペナルティ後に相手ディフェンスエリアに侵入しないように、待機位置を変更した

consai_examples/consai_examples/field_observer.py
#82 の対策
パス関数起動時にロボットの座標などの値を格納していたが，代入文では元々の変数の値が変化するとその変数の値も変化する
そのため，参照タイミングの違いによって値がある/ないが変わっていました
その対策としてdeepcopyで確定した値を格納しています
=> 速度参照タイミングの違いでNoneにならないようにdeepcopy()で値を取得

consai_examples/consai_examples/field_observer.py
ディフェンスエリアにボールが入った判定を広げます
これにより「 Attacker touched ball inside opponent defense area」の発生を防ぎます。
- ロボットが部分的にもしくは完全に相手チームのディフェンスエリアにある間、そのロボットはボールに接触してはならない。
=> アタッカーがディフェンスエリアに侵入しないように、ball_in_defence_areaのyを広げた

consai_msgs/CMakeLists.txt, consai_msgs/msg/GoalPoses.msg, consai_robot_controller/include/consai_robot_controller/controller_component.hpp, consai_robot_controller/include/consai_robot_controller/field_info_parser.hpp, consai_robot_controller/src/controller_component.cpp, consai_robot_controller/src/field_info_parser.cpp, consai_visualizer/src/consai_visualizer/field_widget.py, consai_visualizer/src/consai_visualizer/visualizer.py
#88 でfinal_goal_poseトピックを登場させましたが、トピック数がロボット台数分多くなり、処理が重くなりました。
`goal_poses`と`final_goal_poses`にトピックを集約し、処理を軽くします。
=> goal_poses型を作って、goal_poseとfinal_goal_poseを集約した

consai_visualizer/src/consai_visualizer/field_widget.py
GUIでgrsimのボールを動かすとき、ボールが弾け飛ぶ問題を解決します。
再配置時の速度を0にすることで解決しました。
=> grSimのボールを動かすとき、ボールが弾け飛ぶのを解決する

consai_examples/consai_examples/game.py, consai_examples/consai_examples/referee_parser.py
refereeがFORCE_STARTを発行したとき、game.pyで"UNDEFINED REFEREE COMMAND" と出力されていました。
force_startフラグを追加して解決します。
game.pyにて、force_start時はinplay()動作を実行します。
=> refere_parserにforce_startフラグを追加

consai_examples/consai_examples/field_observer.py
#82 の対応
原因を探ったところ，ロボットIDの数と速度や位置の数が違うことが原因
少なくともIDの更新位置を変えたのでエラーは起こらないはず
変更前：ゴーリーのパス判定を行うところで位置情報がないためにNoneTypeエラーを出していた
=> Fix pass func error

consai_visualizer/resource/visualizer.ui, consai_visualizer/src/consai_visualizer/field_widget.py, consai_visualizer/src/consai_visualizer/visualizer.py
BLUE, YELLOWの下にフィールド上のロボット台数を表示します
=> visualizerロボット台数を表示する

consai_examples/consai_examples/game.py
=> アタッカーの不要な切り替わりを防ぐ

consai_examples/consai_examples/control.py, consai_examples/consai_examples/robot_operator.py, consai_msgs/msg/ConstraintLine.msg, consai_robot_controller/src/field_info_parser.cpp
ConstraintLineに交点からのオフセットを設定するための`offset_intersection_to_p2`を追加します。
control.pyの`test_defend_goal_on_line`を実行すると動作を確認できます。
=> ConstraintLineに交点からのオフセットを追加

consai_robot_controller/include/consai_robot_controller/field_info_parser.hpp, consai_robot_controller/src/field_info_parser.cpp
ボール周囲の回避を改善します。
- ボールの円周上を移動して回避する処理を削除します
- デフォルトでobstacle_avoidance()でのボール回避が働くのではずしました
- フィールド外に目標位置が出たとき、フィールド内に目標位置をずらす
=> ボール500mm回避の処理を更新。フィールド外に目標位置を生成しない

consai_visualizer/src/consai_visualizer/visualizer.py
リセットタイマーが干渉していたことにより、プレースメントの描画が継続していた。
=> ビジュアライザのリセットタイマーが干渉していたので修正

consai_examples/consai_examples/role_assignment.py
ゴール前DFがボールを持ってもロールがアタッカーにならない問題の対応です
=> ボールに非常に近い距離でのアタッカー切り替え判定を変更

consai_robot_control_utils/README.md, consai_robot_control_utils/launch/rqt_plot.launch.py
rqt_plotの起動が簡単になります。
例：`ros2 launch consai_robot_control_utils rqt_plot.launch.py robot_id:=10 yellow:=true`
=> consai_robot_control_utilsにrqt_plot起動用のlaunchファイルを追加

consai_robot_controller/src/field_info_parser.cpp
元々複雑な処理だったが中間パスの生成点を2点だけに絞りシンプルにした
- ボールより前にロボットが存在する場合：ボールの斜め後ろに中間パスを生成
- ボールより後ろにロボットが存在しているがボールの背後にいない場合：ボールの後ろのマージンをもたせた位置に中間パスを生成、このときドリブラーもON
=> ボールアプローチをシンプルに改良

consai_vision_tracker/src/visualization_data_handler.cpp, consai_visualizer/src/consai_visualizer/field_widget.py
#133 を解決します
- ロボットの外形線を太くしました
- ロボット前面の直線部分を長くしました
=> ロボットの向きをわかりやすくする

consai_examples/CMakeLists.txt, consai_examples/consai_examples/ball_boy_test.py, consai_examples/consai_examples/operation.py, consai_examples/tests/test_operation.py, consai_msgs/action/RobotControl.action, consai_robot_controller/CMakeLists.txt, consai_robot_controller/include/consai_robot_controller/ball_boy_tactics.hpp, consai_robot_controller/include/consai_robot_controller/field_info_parser.hpp, consai_robot_controller/src/ball_boy_tactics.cpp, consai_robot_controller/src/field_info_parser.cpp
ボールボーイロボの制御関数を追加します。
`RobotControl`アクションの`ball_boy_dribble_enable`をtrueにすると、
ボールボーイロボのボール運び動作を実行します。
下記の内容が未実装です。
- ボールへ近づくときのボール回避
- 長方形フィールドへの対応（角のボールが取れない）
- ボールボーイロボのテスト関数を追加します
- BallBoyTacticsクラスを追加します
=> ボールボーイロボの制御を追加

consai_examples/CMakeLists.txt, consai_examples/consai_examples/operation_test/shoot_to_their_test.py
=> 無限シュートのテストを移植

consai_vision_tracker/src/ball_tracker.cpp
カルマンフィルタで使用しているボールのシステムノイズを大きくします。
#145 でノイズを小さくしましたが、ボールをキックした瞬間にボールを見失うので、値を変更します。
=> ボールのシステムノイズを変更

consai_robot_controller/src/field_info_parser.cpp
キックオフ時にロボットが反転しないことを確認しました。
Close #129
=> STOP中のボール500 mm回避で、目標角度が反転する問題を修正

consai_examples/consai_examples/game.py, consai_examples/consai_examples/referee_parser.py
得点が決まったときのレフェリー信号（14, 15）に対応します。
Close #161 
AutoRefereeを起動し、goal blue、goal yellow判定を出してもロボットがHALTされていることを確認しました。
=> goal blueとgoal yellow信号に対応

.docker/consai-grsim-compose.yml, .github/workflows/scenario_test.yaml
ロボットを同時に複数turn offするとgrSimがクラッシュする問題があります。
https://github.com/RoboCup-SSL/grSim/issues/185
それを回避するため、SSL-RootsでフォークしたgrSimをシナリオテストCIに使用します。
=> Use ssl-roots/grsim for scenario test

.github/workflows/scenario_test.yaml, consai_examples/launch/start.launch.py
シナリオテストのログを記録します。
シナリオテストに失敗すると、ビジョンとレフェリーのログが保存されます。
ログファイルはssl-log-playerで再生できます。
https://github.com/RoboCup-SSL/ssl-go-tools/tree/master
--- 
シナリオテストツールの参考PR：https://github.com/SSL-Roots/robocup_scenario_test/pull/15
=> Logging scenario test

consai_examples/consai_examples/game.py, tests/test_scenario_force_start.py, tests/test_scenario_halt.py, tests/test_scenario_kickoff.py, tests/test_scenario_stop.py
game.pyの更新周期を100 Hzにします。
これにより、inplay中の遅延が改善されるはずです。
また、次のシナリオテストを追加します。
特にFORCE STARTのテストは、今回の不具合改善の検証として追加しています。
- FORCE STARTからHALTに遷移し、2秒以内にすべてのロボットが停止すること
- STOP中にボールを転がし、すべてのロボットが1.5 m/s以下の速度で移動すること
- STOPからFORCE STARTに遷移し、theirゴールにボールをシュートし得点すること
=> Add scenario tests

consai_examples/consai_examples/game.py, consai_examples/consai_examples/operation.py, consai_examples/consai_examples/robot_operator.py, consai_msgs/CMakeLists.txt, consai_msgs/msg/RobotControlMsg.msg, consai_robot_controller/include/consai_robot_controller/controller_component.hpp, consai_robot_controller/include/consai_robot_controller/field_info_parser.hpp, consai_robot_controller/include/consai_robot_controller/obstacle/obstacle_observer.hpp, consai_robot_controller/src/controller_component.cpp, consai_robot_controller/src/field_info_parser.cpp, consai_robot_controller/src/obstacle/obstacle_observer.cpp, consai_robot_controller/test/obstacle_observer_test.cpp, consai_tools/consai_tools/hasher/robot_control_hasher.py
game側で、ロボットの目標位置を動的に変更することが多くなっています。
RobotControl.actionでは、動的な目標位置変更に対応することが難しいです。
NamedTargetを使えば可能ですが、実装としてわかりにくいです。
Action通信をやめてTopic通信を採用します。
Actionならではの、成功失敗判定や、行動中のフィードバックが使えなくなります。（今もあまり使ってないのですが。。。）
この対策として、行動完了トピックをcontrollerから配信予定です。別PRで対応します。
- シナリオテストが通ることを確認します
- 試合プログラムを実行し、大きな挙動変化が無いことを確認します。
=> Action通信をやめて、Topic通信でcontrollerに指令を送る

consai_examples/consai_examples/decisions/attacker.py, consai_examples/consai_examples/observer/pass_shoot_observer.py, consai_robot_controller/CMakeLists.txt, consai_robot_controller/include/consai_robot_controller/field_info_parser.hpp, consai_robot_controller/include/consai_robot_controller/tactic/shoot_tactics.hpp, consai_robot_controller/include/consai_robot_controller/tactic/tactic_data_set.hpp, consai_robot_controller/src/field_info_parser.cpp, consai_robot_controller/src/tactic/shoot_tactics.cpp, consai_tools/include/consai_tools/geometry_tools.hpp, consai_tools/src/geometry_tools.cpp, tests/test_scenario_ball_placement.py
パスとシュートをshoot_tacticsに実装します
パス威力のリミットを調整したので、
#135 をクローズできます。
#132 に関連して以下の変更が行われます。
- 中間位置に収束したかどうかが毎回発生することで遅い気がする　：　改善されます
- タイガースがやっているクルッと回って蹴るやつやりたい　：　実装しました
- ボール取るときに右肩タックルする　：　おそらく改善します。実機検証が必要です
- ボールをなかなか蹴らない　：　おそらく改善します。実機検証が必要です。
- 衝突回避により、相手 or 味方がボール持っているときに取れない　：　改善します。
- 完全にフリーな状態のボールを取りに行くときにも謎の回避動作がはいってしまう　：　改善します。
- ボールアプローチがあまりにも遅い　：　おそらく改善します。実機検証が必要です
Attackerの行動をmove_to_poseからmove_on_lineに変更しています。
下記の記述をすると、目標角度が強制的に0度になるためです。
```python
move_to_ball = Operation().move_to_pose(TargetXY.ball(), TargetTheta.look_ball())
```
=> Add shoot_tactics

consai_examples/consai_examples/decisions/attacker.py, consai_robot_controller/include/consai_robot_controller/tactic/shoot_tactics.hpp, consai_robot_controller/include/consai_robot_controller/tactic/tactic_data_set.hpp, consai_robot_controller/src/field_info_parser.cpp, consai_robot_controller/src/tactic/shoot_tactics.cpp, tests/test_scenario_ball_placement.py
shoot_tactics にセットプレイのフラグを追加します。
セットプレイ時は、ボール周りを旋回するときの半径を広くします。
これにより、ボールプレースメント後にボールへ衝突する問題を解決します。
Close #162 
また、セットプレイ時の遠くからボールへ向かうときの目標角度が0度になっていたので、ボールを向くように修正します。
=> Update setplay motion.

consai_examples/consai_examples/decisions/attacker.py, consai_examples/consai_examples/game.py, consai_examples/consai_examples/observer/pass_shoot_observer.py
アタッカーの動作にsetplay時の処理を追加しました。
動作順は以下のとおりです。
1. パス可能な味方ロボットにパスする
2. シュート可能な相手ゴールにシュートする
3. 1と2ができないときは相手ゴール中心にシュートする
=> setplay時のアタッカー動作追加

consai_examples/consai_examples/role_assignment.py, consai_examples/tests/test_role_assignment.py
sub_attackerの優先度を3番目にします。
これにより、ロボット台数が減ってもボールプレースメントが実行可能になります。
ただし、ディフェンスの台数が減ってしまいます。
Close #165
=> Update role priority

consai_tools/include/consai_tools/geometry_tools.hpp, consai_tools/src/geometry_tools.cpp, consai_vision_tracker/CMakeLists.txt, consai_vision_tracker/include/consai_vision_tracker/ball_tracker.hpp, consai_vision_tracker/include/consai_vision_tracker/robot_tracker.hpp, consai_vision_tracker/package.xml, consai_vision_tracker/src/ball_tracker.cpp, consai_vision_tracker/src/tracker_component.cpp
ボールのカルマンフィルタについての変更です。
ボールがロボット近傍にあるかどうかで、システムモデルの不確かさを切り替えます。
これにより、キックされたボールの軌道がより直線に近づきます。
ロボット付近にボールがあるときは不確かさが大きいので、
ボールを蹴った直後にボール予測位置が消失するという問題を避けられます。
Close #220
=> Switch ball system model of KF when ball is far from robots.

consai_vision_tracker/include/consai_vision_tracker/robot_tracker.hpp, consai_vision_tracker/src/robot_tracker.cpp, tests/test_scenario_ball_placement.py, tests/test_scenario_force_start.py, tests/test_scenario_free_kick.py, tests/test_scenario_kickoff.py, tests/test_scenario_penalty.py, tests/test_scenario_stop.py, tests/yellow_invert/test_scenario_yellow_invert_kickoff.py
#224 で実施した誘拐対策をロボットにも適用します。
これにより、誘拐後の収束時間が短くなります。
また、シナリオテストでロボット配置後のsleep時間が不要になるため、
全シナリオテストからsleepを極力除去します。
また、できるだけ多くのロボットをシナリオテストで動かします。
=> ロボットのカルマンフィルタに誘拐対策を実装。シナリオテストでできるだけ全ロボットを使用する。

consai_examples/consai_examples/decisions/attacker.py, consai_examples/consai_examples/operation.py, consai_robot_controller/include/consai_robot_controller/tactic/shoot_tactics.hpp, consai_robot_controller/src/tactic/shoot_tactics.cpp
下記の変更を実施します
- Attackerのour directでセットプレイキックを使う
- ボール周りで旋回するときの速度を変更
- ROTATEからSHOOTに遷移するときにキック目標位置を固定する
- 直進走行がブレることを防ぎます
Close #229
=> シュート関連のパラメータ更新

consai_examples/CMakeLists.txt, consai_examples/consai_examples/decisions/decision_base.py, consai_examples/consai_examples/decisions/side_back.py, consai_examples/consai_examples/field_observer.py, consai_examples/consai_examples/game.py, consai_examples/consai_examples/observer/side_back_target_observer.py, consai_examples/consai_examples/role_assignment.py
ディフェンスエリアの横をまもります。  
ディフェンスエリアの横に相手ロボットがいたら、そいつをマンマークします。  
それ以外はてきとうな位置で待機します。  
サイドウィングたちをリストラしています。  
いまゾーンディフェンスと動きがかぶっている部分がありますが、それはゾーン側を直すべきなので一旦無視してください。  
マンマーク対象が被る問題があります。
=> Sideback追加

consai_examples/consai_examples/decisions/side_wing.py, consai_examples/consai_examples/decisions/sub_attacker.py
タイトル通り
inplay中にサブアタッカーとサイドウィングが相手ゴールにシュート可能であればシュートするように変更
=> サブアタッカーとサイドウィングにinplay時シュートできるときにシュートするように変更

consai_examples/consai_examples/decisions/goalie.py
従来はボールとゴール中心を結ぶ直線を基準に守っていたが、ボールとゴール裏の座標を結ぶ直線に変更
=> ゴーリーの守り位置を調整

consai_examples/consai_examples/decisions/attacker.py, consai_examples/consai_examples/observer/pass_shoot_observer.py
バックパスができていなかったのでできるようにパス関数を変更しました
現状は0.5m後ろのロボットまでバックパス対象にしています
**ロボットがモジモジしてなかなか蹴り出さなかった理由**
1. ボールに近づく
2. ボール直下にいるサブアタッカーがパスを出すロボットの前後をウロウロする
3. パスがなかなか出せない
となっていました。
バックパス実装に伴って解消されています。
=> バックパスができるようにパス関数を変更

consai_robot_controller/src/field_info_parser.cpp, consai_robot_controller/src/tactic/tactic_obstacle_avoidance.cpp
ディンフェスエリアの衝突回避を最大にします
ボール周囲500 mm回避よりも優先度が高くなるので、ディンフェスエリア付近にボールがあるときの挙動が怪しいかもしれません。
（STOP中はディフェンスエリアからボールを700 mm以上離すので、大丈夫だと思いますが）
=> Set max priority for defense area avoidance

consai_examples/CMakeLists.txt, consai_examples/consai_examples/field_observer.py, consai_examples/consai_examples/game.py, consai_examples/consai_examples/observer/man_mark_observer.py, consai_examples/consai_examples/role_to_visualize_msg.py
マンマーク用のObserverを追加します。
次のようにマーク対象のIDを取得できます
```python
observer.man_mark().set_our_active_bot_ids([1, 2, 3])
target1 = observer.man_mark().get_mark_robot_id(1)
target2 = observer.man_mark().get_mark_robot_id(2)
if target1 == -1:
return
```
現在は、座標がx < 0 となる相手ロボットをマーク対象とし、
それに一番近い味方ロボットを割り当てています。
アルゴリズムは適宜変更してください。
（例：ボールまでの距離が3 m 以内のロボット）
ビジュアライザにマーク対象の結果を表示します。
デバッグにも役立ちます。
本来は単体テストを書くべきですが、サボってます。
ざっくりと下記のテストを実行してます。
- 味方ロボットの増減に対応しているか
- 相手ロボットの増減に対応しているか
- 自エリアの侵入と脱出に対応しているか
- 自エリアに侵入した相手ロボットの移動に対応しているか
- ロールの切り替わりに対応しているか
このobserverを使うことで、
#241 のゾーンマンマークをより強くできると思います。
=> Add man mark observer

consai_examples/consai_examples/decisions/center_back.py, consai_examples/consai_examples/operation.py, consai_msgs/msg/RobotControlMsg.msg, consai_robot_controller/include/consai_robot_controller/tactic/tactic_obstacle_avoidance.hpp, consai_robot_controller/src/field_info_parser.cpp, consai_robot_controller/src/tactic/tactic_obstacle_avoidance.cpp
衝突回避のオプションに、自チームと相手チームのロボット回避をON/OFFするものを追加しました。
これにより、センターバックがお互いに衝突回避することを抑えられます。
センターバックは、自チームのゴールに近づいたときに、自チームロボットの回避をOFFします。
Close #232
=> センターバックがお互いを衝突回避しない。

consai_examples/CMakeLists.txt, consai_examples/consai_examples/decisions/zone_defense.py, consai_examples/consai_examples/field_observer.py, consai_examples/consai_examples/observer/man_mark_observer.py, consai_examples/consai_examples/observer/side_back_target_observer.py, consai_examples/consai_examples/observer/zone_man_mark_target_observer.py, consai_examples/consai_examples/observer/zone_target_observer.py
これまでゾーンDFは自分の担当エリアに入ってきたロボットに反応していましたが、  
自陣に入ってきたロボットをゴールから近い順にマークするように変更しました。  
相手ロボットとボールの間に入ろうとします。
自陣側、かつ、DFエリアより前　の区画です。  
DFエリアより後ろはサイドバックにおまかせします。
近い順に、ZONE IDが若い順にマーク位置へ移動します。  
ほかは待機します。  
本当はマークしてるロボットの台数におうじて、待機ロボットの位置を変更していったほうが良い気がしますが  
そこはやってないです。
=> ゾーンマンマークを追加

consai_examples/CMakeLists.txt, consai_examples/consai_examples/decisions/attacker.py, consai_examples/consai_examples/game.py, consai_examples/consai_examples/role_assignment.py, consai_examples/consai_examples/role_to_visualize_msg.py
ロールアサインの更新です。
ボールが動いている場合、ボール軌道に近いロボットをアタッカーにします。
このPRは、FORAWRDロールを作った場合に本領発揮します（多分）
=> Use ball trajectory for attacker role assignment

consai_examples/consai_examples/decisions/side_back.py, consai_examples/consai_examples/observer/side_back_target_observer.py
- マーク対象をx座標でみてましたが、ゴールに近い方が怖いのでy座標に切り替えました
- DFエリアから遠いロボットを深追いしないように、しきい値を設けました
- しきい値をこえたマーク対象に対しては、DFエリアサイドと水平方向にマークします
ゴールに近い方を優先かつ、しきい値以内なのでマンマーク
しきい値より遠いので、DFエリアサイドから離れすぎない位置でマーク
=> サイドバックの行動を修正

consai_examples/consai_examples/decisions/attacker.py, consai_examples/consai_examples/decisions/sub_attacker.py, consai_examples/consai_examples/field.py, consai_examples/consai_examples/game.py, consai_examples/consai_examples/observer/ball_position_observer.py, tests/test_scenario_ball_placement.py
- ドリブルで受けるときのサブアタッカーがもじもじしないようにした  
- ロールアサインのせいで、アタッカーが遠くに蹴ったあとすぐにサブアタッカーになって全力で追いかけるのをやめました
- フィールドから出た判定のちょっと甘い版をつくりました
- こけがちなシナリオテストを一旦はぶきました
=> ボールプレースメント修正

consai_robot_controller/src/tactic/shoot_tactics.cpp
これを改善した気がする  
https://github.com/SSL-Roots/consai_ros2/issues/263
ずるずる移動していたときは SHOOTのステートにはいっていました。  
このときロボットがボールを正面でもっているかどうかを判断していなかったので  
へんな位置でSHOOTに入っていたときは、アプローチに戻るようにしました。  
あとはへんなしきい値がはいっていたので、消しました。
=> ボールアプローチ改善

consai_examples/consai_examples/decisions/goalie.py
以前の敵ロボットのキー検索にバグがある可能性があった
以前は距離順にソートしてインデックスを取得しようとしていたが、今回は最小値のインデックスだけ順番に取得して検索している
=> 敵ロボット位置のキー検索を変更（ゴーリー）

consai_examples/consai_examples/decisions/attacker.py, consai_examples/consai_examples/operation.py, consai_msgs/msg/RobotControlMsg.msg, consai_robot_controller/CMakeLists.txt, consai_robot_controller/include/consai_robot_controller/field_info_parser.hpp, consai_robot_controller/include/consai_robot_controller/tactic/back_dribble_tactics.hpp, consai_robot_controller/src/field_info_parser.cpp, consai_robot_controller/src/tactic/back_dribble_tactics.cpp
バックドリブル機能を追加します。
これを用いて、ボールプレースメント時に、壁際のボールをドリブルで吸い出します。
シュート処理の影響により、ボール吸い出したあと、ドリブラーを回しながらくるくるロボットが動くことがあります。
別PRで直します。
=> Use back dribble for ball_placement

consai_examples/consai_examples/decisions/sub_attacker.py, consai_examples/consai_examples/game.py, consai_examples/consai_examples/role_assignment.py
サブアタッカーを2第荷増やしました。
それに伴ってゾーンディフェンスの台数を4台から3台に減らしました。
サブアタッカーは相手ペナルティーエリア周辺に移動します。
フェール度中心から相手側コートの0.5mまでは自分たち側にボールがあるものとして処理しています。
→キックオフのときに相手側に居座り続けて大量に違反が取られるため
=> Update sub attacker

.docker/consai-grsim-compose.yml, .github/workflows/scenario_test.yaml
CI用のdockerイメージをビルドしてから、シナリオテストを実行するように構造を変更します。
これにより、シナリオテストを再実行する際のconsaiビルドステップを省略できます。
=> Use CI image for scenario test

.github/workflows/scenario_test.yaml
Dockerイメージ作成とpythonライブラリセットアップは独立しているので、同時に動かします。
=> Fix job dependencies of scnario_test CI.

consai_game/consai_game/world_model/referee_model.py, consai_game/consai_game/world_model/world_model_provider_node.py
lockを使って安全にデータを更新できるようにreferee_model周りをリファクタリングします。
APIに変更はありません。
=> Refactor referee_model to use lock

consai_game/consai_game/world_model/ball_position_model.py, consai_game/consai_game/world_model/world_model.py, consai_game/consai_game/world_model/world_model_provider_node.py
consai_examples/consai_examples/observer/ball_position_observer.py でやってたことほぼそのまま
以下確認用
```
print(f'is_in_our_defense_area: {self.world_model.ball_position.is_in_our_defense_area()}')
print(f'is_in_their_defense_area: {self.world_model.ball_position.is_in_their_defense_area()}')
print(f'is_in_our_side: {self.world_model.ball_position.is_in_our_side()}')
print(f'is_in_their_side: {self.world_model.ball_position.is_in_their_side()}')
print(f'is_outside_of_left: {self.world_model.ball_position.is_outside_of_left()}')
print(f'is_outside_of_right: {self.world_model.ball_position.is_outside_of_right()}')
print(f'is_outside_of_top: {self.world_model.ball_position.is_outside_of_top()}')
print(f'is_outside_of_bottom: {self.world_model.ball_position.is_outside_of_bottom()}') …
```
=> ball position modelを追加

consai_game/consai_game/core/play/play_node.py, consai_game/consai_game/core/role_assignment/factory.py, consai_game/consai_game/core/role_assignment/methods/by_visible.py, consai_game/launch/start.launch
フィールドに現れた順にロールアサインする`by_visible`メソッドを追加します。
先頭のロールを優先的に　かつ　ロールの交代が最小限になるように割り当てます。
また、STOPゲーム中にconsaiを起動するとplayが見つからずにエラーが出る場合があります。
対策としてapplicableなplayがなくても例外が発生しないようにしました。
ロボットのON/OFFを繰り返し、エラーなくロボットがアサインされることを確認しました。
=> Add by_visible role assignment.

consai_game/CMakeLists.txt, hooks/run_ament_black.sh, hooks/run_ament_flake8.sh, hooks/run_ament_pep257.sh, pyproject.toml, setup.cfg
設定ファイルを設置
- setup.cfg
- pyproject.toml
hookのファイルも設定ファイルを読めるように変更
=> python関係のpre-commitについて，行の長さを120文字までに変更

consai_game/consai_game/world_model/ball_position_model.py, consai_game/consai_game/world_model/field_model.py, consai_game/consai_game/world_model/world_model_provider_node.py, setup.cfg
チケット：https://github.com/orgs/SSL-Roots/projects/7/views/1?pane=issue&itemId=106158744
- ament_flake8を満たすようにコードを整形
- 以下のメンバ変数として登録し，`self._field.length / 2`などを置き換えた
```python
half_length = length / 2
half_width = width / 2
half_goal_width = goal_width / 2
half_penalty_depth = penalty_depth / 2
half_penalty_width = penalty_width / 2
```
=> フィールドの半分の長さをメンバ変数として用意

consai_game/consai_game/core/role_assignment/factory.py, consai_game/consai_game/core/role_assignment/methods/by_cost.py, consai_game/launch/start.launch
Tacticへの移動距離が最小になるRoleアサイン方法を追加します。
下記のコマンドで実行できます
```sh
ros2 launch consai_game start.launch goalie:=0 assign:=by_cost
```
- ロボット数よりRole数のほうが多い場合、Role1にロボットがアサインされない可能性があります
- そのため、「Role1がボールを扱う」　という処理を書いているとうまく動きません
=> Add by_cost role assignment

consai_game/consai_game/main.py, consai_game/consai_game/world_model/kick_target_model.py, consai_game/consai_game/world_model/visualize_msg_publisher_node.py
WorldModelの描画用に、visualize_msg_publisher_nodeを追加します。
まずはkick_targetを描画します。
描画するためにkick_targetの変数を変更しています（グローバルにアクセスするため、アンダーバーを消す）
kick_targetを使うshoot tacticに影響します。動作は変化なかったので問題なしです。
=> Visualize kick_target

consai_game/consai_game/world_model/threats_model.py, consai_game/consai_game/world_model/visualize_msg_publisher_node.py, consai_game/consai_game/world_model/world_model.py, consai_game/consai_game/world_model/world_model_provider_node.py
https://github.com/orgs/SSL-Roots/projects/7/views/1?pane=issue&itemId=107270074
やばいロボットランキングを実装したよ
ゴールへの距離、シュートできそうか、ボールに近いかを
4:3:3の割合で評価しているよ
特に根拠はないから調整するべきだよ
ローパスフィルターも一応いれているよ
alphaをいじって調整するべきだよ
いまの値に根拠はないよ
GUIのgameのところに項目を追加したので敵の上に驚異度が出るよ
順位とスコアが表示されるよ
終わりだよ
=> やばいロボットランキングモデルを追加

consai_game/consai_game/world_model/kick_target_model.py, consai_game/consai_game/world_model/visualize_msg_publisher_node.py
kick_target_modelのリファクタリング
チケット→https://github.com/orgs/SSL-Roots/projects/7?pane=issue&itemId=107441577
- kick_target_listはshoot_target_listに改名
- best_target_indexを廃止
- best_target_indexがなくなったことで描画するコードで存在しない変数参照しようとしていたため、修正
- shoot_targetのスコア計算の際にすべてのターゲットの計算結果を加算し続けていたので修正
- スコア計算が正常になりましたけど、成功率を割り出す処理もう少し賢くしたい
- 計算上のロボット半径を実際のロボットの直径に設定してそれでもシュート決めるところの成功率引き上げとかしたほうがいいかもしれません
=> Refactor kick target to shoot target

robocup_ssl_comm/include/robocup_ssl_comm/multicast.hpp
vision_addrとreferee_addrに`127.0.0.1`をセットしても、通信可能にしました。
=> Support local loopback address for visoin and referee

consai_game/consai_game/play/factory/simple_plays.py, consai_game/consai_game/tactic/composite/composite_offense.py, consai_game/consai_game/tactic/kick/kick.py
パス・シュートを結合した`CompositeOffense`というTacticを追加します
自身がボールに一番近ければ、パスかシュートをする。
近くなければデフォルトのtactic （コンストラクタ引数で設定）　を実行する。
という処理が組み込まれてます。
インプレイ中のPlayを書くとき、ひとまず`CompositeOffense`を全ロボットに設定すればよいです。
これにより、playファイルには陣形を書くだけになります。
（誰がパサーで、誰がシューターか、などを気にしなくてOK）
- ボールの受け取り機能が未実装
- ボールのドリブル機能が未実装
- パスもシュートもできないときは、その場でくるくる回るような動作になります。
=> Add CompositeOffense tactic

consai_game/consai_game/tactic/composite/composite_offense.py, consai_game/consai_game/world_model/ball_activity_model.py, consai_game/consai_game/world_model/robot_activity_model.py, consai_game/consai_game/world_model/visualize_msg_publisher_node.py, consai_game/consai_game/world_model/world_model_provider_node.py, consai_tools/consai_tools/geometry/geometry_tools.py
ボールを受け取れるランキングをRobotActivityModelに追加します。
また、CompositeOffenseでボールを受け取れるようにします。
こんな感じに使用できます。
```python
best_receive_score = world_model.robot_activity.our_ball_receive_score[0]
if world_model.ball_activity.ball_is_moving:
if best_receive_score.robot_id == self.robot_id and best_receive_score.intercept_time != float("inf"):
```
scoreのintercept_timeにはボールを受け取るまでの時間が入ります。受け取れない場合はinfです。
- ball_activity_modelからrobot_activityの依存関係を取り除きました
- robot_activityがball_activityの情報を使うためです。（対策しないと循環参照する）
- ボールを後ろから追いかけて受け取ることには対応してません。
- ボールが減速して止まることは考慮してません
- ロボットの初速度と加速度は考慮してません
=> Add our_ball_receive_score in robot_activity_model. CompositeOffense can receive ball.

.devcontainer/local-dev/Dockerfile
RCST https://github.com/SSL-Roots/robocup_scenario_test
をlocal dev conatinerで使用可能にします
=> Install rcst in devcontainer

consai_game/consai_game/core/tactic/agent.py, consai_game/consai_game/core/tactic/tactic_base.py, consai_game/consai_game/tactic/composite/composite_offense.py, consai_game/consai_game/tactic/position.py
TacticBaseにreset関数とexit関数を追加します
reset関数を抽象関数から通常の関数に変更し、
これまで各Tacticに実装していたコードを移植しています。
もし、各Tacticでオリジナルのreset関数を実装したい場合は`super().reset(robot_id)`を呼んでください
例として、`CompositeOffense`と`Position`を書き換えてます。
Tacticにデストラクタ的な関数がほしい。という要望をもとに実装しました。
Tacticが切り替わるときに実行されます。
=> Implement reset and exit methods to TacticBase

consai_game/consai_game/play/factory/running_plays.py, consai_game/consai_game/play/factory/simple_plays.py, consai_game/consai_game/tactic/defend_goal.py, consai_game/consai_game/tactic/wrapper/allow_move_in_defense_area.py, consai_game/consai_game/tactic/wrapper/wrapper_look_ball.py
AllowMoveInDefenseAreaというWrapperを追加します。
次のように使用できます
```python
AllowMoveInDefenseArea(DefendGoal())
```
また、GoalieをすべてのPlayに追加しました。
- もともとDefendGoalで設定していたNaviOptionsを取り除きました。
=> Add allow_move_in_defense_area wrapper. Implement goalie to all play

consai_game/consai_game/tactic/slow_safe_position.py, consai_game/launch/start.launch, consai_msgs/msg/NaviOptions.msg, consai_referee_parser/CMakeLists.txt, consai_referee_parser/consai_referee_parser/main.py, consai_referee_parser/consai_referee_parser/referee_parser_node.py, consai_referee_parser/package.xml, consai_robot_controller/include/consai_robot_controller/field_info_parser.hpp, consai_robot_controller/include/consai_robot_controller/tactic/tactic_obstacle_avoidance.hpp, consai_robot_controller/src/field_info_parser.cpp, consai_robot_controller/src/tactic/tactic_obstacle_avoidance.cpp
レフェリー信号をパースするconsai_referee_parser packagesを追加します。
プレースメント位置（designated_position）をconsai_robot_controllerへ送信するために使用します。
また、将来的にはReferee情報の描画トピックもpublishする予定です。
要するに、consai_examplesにあるparserのコードをここへ移植します。
=> Add consai_referee_parser. Support avoid_placement_area flag of navi_options.

consai_game/consai_game/tactic/defend_goal.py
チケット：https://github.com/orgs/SSL-Roots/projects/7/views/1?pane=issue&itemId=107270418
- ゴール回避を追加した
- sim上でゴール側のフィールド外にゴーリーを置くと回避する様子が見れる
- 遠くに置くと若干ゴールにぶつかるが，そのための処理を今書くのは手間なのでやめた
- 今は突貫工事であり，いずれはcontrollerに入れるべきなので手間をかけるべきではない
=> defend_goal.pyにゴール回避を追加

consai_game/consai_game/main.py, consai_game/consai_game/world_model/game_config_model.py, consai_game/consai_game/world_model/referee_model.py, consai_game/consai_game/world_model/robots_model.py, consai_game/consai_game/world_model/world_model_provider_node.py, consai_game/launch/start.launch, consai_msgs/CMakeLists.txt, consai_msgs/msg/RefereeSupportInfo.msg, consai_referee_parser/consai_referee_parser/referee_parser_node.py, consai_referee_parser/consai_referee_parser/referee_to_vis_msg.py
レフェリー情報の描画を移植しました。
ロボットの台数や、ボール位置などをconsai_referee_parserで実行するのは冗長なので、
[RefereeSupportInfo.msg](https://github.com/SSL-Roots/consai_ros2/compare/feature/referee_gui?expand=1#diff-a3b1f4349695bd0336098db0c4e66f14ea9b4a8ca37572566fed286cc1371b01)という新しいメッセージで情報を渡すことにしました。
=> Visualize Referee Info

consai_game/consai_game/tactic/kick/kick.py
チケットhttps://github.com/orgs/SSL-Roots/projects/7/views/1?pane=issue&itemId=106226779
- chasingでtransを使って位置の候補をtransの座標系から見てボールy軸+-にそれぞれ生成しています
(ピンク：目標位置、オレンジ：ボール、青の座標系：trans、赤動作するロボット)
- 2つの候補位置で近いところを目標位置として向かうようにしています
- aimingとkickingについてavoid_pushingをtrueにしています
- chasingでぶつかるのは想定外だと考えたから
=> Fix kicktactic cannot kick

consai_game/consai_game/core/role_assignment/methods/by_visible.py
by_visibleロールアサインメントで、アサイン配列の先頭側から空席を埋めるように修正します。
=> Fix by_visible role assignment to fill gaps

consai_game/consai_game/tactic/composite/composite_ball_placement.py, consai_game/consai_game/tactic/dribble.py, consai_game/consai_game/tactic/move_to_ball.py, consai_game/consai_game/world_model/visualize_msg_publisher_node.py
ボールプレースメントの動きが不安定だったので修正します。
- ボールが目的位置についたとき、2台のロボットがボールからまっすぐ逃げるようにtacticを変更します
- ドリブル速度をdribble tactic内で調整するように変更します
- 衝突回避のボール回避機能でボールを避けながらapproachします
- approach_ballを調整したかったのですが、複雑だったので別タスクとします。
- ball_next_posの使用をやめます
- ボール速度基準で座標が作られるので、ボール停止時の挙動が不安定です
- ドリブルの動作を、目的位置からの距離に応じて2つに分けます
- 目的位置に近づいたら、ドリブルをオフにしてゆっくり接近します
- これにより、ドリブル終了後のボール移動を抑えられます
ロボットの現在位置からボールへまっすぐ進むTacticです。
ボールへの接近と回避に使用します。
alphaがマイナスになる警告が出てたのでついでに直しました。
プレースメントエリア付近でボールを動かすと、2台のロボットの交代が頻発します。
これは、ボールアプローチ時にボールを大きく回避することで、ボールとロボットの距離が変わるためです。
やはり、ボールアプローチはいい感じに仕上げる必要があります。
=> Fix ball placement motion.

consai_game/consai_game/play/factory/running_plays.py, consai_game/consai_game/tactic/composite/composite_defense.py, consai_game/consai_game/tactic/composite/composite_man_mark.py, consai_game/consai_game/world_model/field_model.py
ほとんどオフェンスの流用です
クリアではなく、一番シュート成功たかいとこにpassするようにしました。
そのほうがワンちゃんあるかなとおもって
すまとらと戦わせていたときのセットです
```
[AllowMoveInDefenseArea(CompositeOffense(DefendGoal()))],
[CompositeOffense(tactic_default=WrapperLookBall(Position(3.0, 2.0)))],
[CompositeOffense(tactic_default=WrapperLookBall(Position(3.0, 0.0)))],
[CompositeOffense(tactic_default=WrapperLookBall(Position(3.0, -2.0)))],
[CompositeDefense(tactic_default=CenterBack())],
[CompositeDefense(tactic_default=CenterBack())],
[CompositeDefense(tactic_default=CenterBack())],
[CompositeDefense(tactic_default=CompositeManMark(tactic_default=WrapperLookBall(Position(-2.0, -2.0))))],
[CompositeDefense(tactic_default=CompositeManMark(tactic_default=WrapperLookBall(Position(-2.0, 2.0))))],
[CompositeDefense(tactic_default=CompositeManMark(tactic_default=Wrap …
```
=> CompositeDefense追加

consai_game/consai_game/world_model/kick_target_model.py
search_shoot_pos関数でデフォルトで味方ロボットを障
害物として計算しないように設定しました。
これにより、ボール基準で相手ゴール側にいる味方ロボットが障害物判定されなくなり、パスを受けたロボットが障害物として認識されなくなりました。
なので優勝です
=> Fix pass action

consai_game/consai_game/tactic/composite/composite_offense.py, consai_game/consai_game/world_model/robot_activity_model.py
ダブルタッチを防ぐ機能を追加します。
`robot_activity.our_prohibited_kick_robot_id`に禁止されているロボットIDがセットされます。
禁止されていない場合は -1 が入ります。
キック禁止ロボットがボールに一番近い、または、ボールを一番レシーブできる場合は、
2番目のロボットが操作するようにしました。
禁止ロボットはデフォルト動作に遷移します。
=> Precent double touch

consai_game/consai_game/tactic/back_dribble.py, consai_game/consai_game/tactic/composite/composite_ball_placement.py, consai_game/consai_game/tactic/dribble.py, consai_game/consai_game/utils/generate_dummy_ball_position.py
ボールプレースメントでボールが消えたときの対策です。
ダミーのボール位置を算出するgenerate_dummy_ball_positionを、ボールプレースメントや、ドリブルに適用します。
これにより、ballがnot is_visibleのときは、"ロボットのドリブラー位置"にボールがあると仮定して、プレースメントを実施できます。
いい感じのタイミングで、grsimのVanishingをON/OFFします
ボールが全くvisibleにならない場合、永遠と仮想位置を算出するため、プレースメントが終わりません。
ボールがフィールド外に出たという判定は、ball_position_modelを使っています。ここには仮想位置を適用できないので、なにか障害があるかもしれません。
=> Use dummy ball position at placement when ball is not visible

consai_game/consai_game/tactic/kick/kick.py
チケット：https://github.com/orgs/SSL-Roots/projects/7/views/1?pane=issue&itemId=108955286
インプレイでのaimingとkickingでドリブラーがONになる
=> ボールに近づいた時ドリブラーを回すよう変更

consai_game/consai_game/tactic/back_dribble.py
バックドリブルでボールを壁際から吸い出すとき、ボールを持つ前にボールから離れることがありました。
これを対策します。
grsimで、ノイズ 15、vanishing 0.3 でもバックドリブルできることを確認しました。
=> Fix robot_has_ball threshold of back_dribble

consai_game/consai_game/play/factory/simple_plays.py
チケット：https://github.com/orgs/SSL-Roots/projects/7?pane=issue&itemId=108995085
単純に設定を忘れていた
=> ball placement時にゴーリーがディフェンスエリア回避をしないよう変更

consai_game/consai_game/tactic/ball_approach.py
チケット：https://github.com/orgs/SSL-Roots/projects/7/views/1?pane=issue&itemId=108712264
- 最初は新しいファイルを作ろうとしたけど，浮いたball_approachを改造した
- 中身はほとんどkickなので，いつかkickへの流用も考えたい
=> ボールを追いかけて受け取るボールアプローチを作成

.gitignore, consai_visualizer/default_consai_visualizer_settings.json, consai_visualizer/src/consai_visualizer/visualizer.py
- ビジュアライザーの表示設定が起動のたびに切り替わってしまう問題があったのでその対応をしました
- 普段の開発のイライラが減ってハッピー
- 実際の試合中、エラー＆再起動しても、表示設定が維持されていて安心
- チケットURL: https://github.com/orgs/SSL-Roots/projects/9/views/1?pane=issue&itemId=110118799
- 変更 .gitignore
- 変更 consai_visualizer/src/consai_visualizer/visualizer.py
- 追加 consai_visualizer/default_consai_visualizer_settings.json
- consai起動
- GUIの表示設定を色々変更後、consai終了
- consai再起動、設定が維持されていることを確認
- これを何回か繰り返す
ビジュアライザーの変更なので、以下は実施してないです
- ビジュアライザーのみ
- ビジュアライザー起動後、確実に設定を反映させるために、設定が反映されるまで3秒弱タイムラグがあります
=> 起動時のGUI表示コンテンツがONしたりOFFしたり不安定問題に対応
